# Generated by Django 6.0.2 on 2026-02-15 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("LAB_MANAGER", "Lab Manager"),
                            ("SUPERVISOR", "Supervisor"),
                            ("TECHNICIAN", "Technician"),
                            ("READER", "Reader"),
                            ("PHYSICIAN", "Physician"),
                        ],
                        help_text="Role identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable role name", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of role responsibilities"
                    ),
                ),
                ("can_view_patients", models.BooleanField(default=True)),
                ("can_edit_patients", models.BooleanField(default=False)),
                ("can_create_patients", models.BooleanField(default=False)),
                ("can_view_samples", models.BooleanField(default=True)),
                ("can_edit_samples", models.BooleanField(default=False)),
                ("can_create_samples", models.BooleanField(default=False)),
                ("can_delete_samples", models.BooleanField(default=False)),
                ("can_view_results", models.BooleanField(default=True)),
                ("can_enter_results", models.BooleanField(default=False)),
                ("can_review_results", models.BooleanField(default=False)),
                ("can_approve_results", models.BooleanField(default=False)),
                ("can_release_reports", models.BooleanField(default=False)),
                ("can_manage_equipment", models.BooleanField(default=False)),
                ("can_manage_reagents", models.BooleanField(default=False)),
                ("can_manage_storage", models.BooleanField(default=False)),
                ("can_view_analytics", models.BooleanField(default=False)),
                ("can_export_data", models.BooleanField(default=False)),
                ("can_import_data", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
                ("can_view_audit_logs", models.BooleanField(default=False)),
                ("can_configure_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Django permissions associated with this role",
                        related_name="lims_roles",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Employee ID or badge number",
                        max_length=50,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Department or section", max_length=100
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, help_text="Job title", max_length=100),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Work phone number", max_length=20
                    ),
                ),
                (
                    "extension",
                    models.CharField(
                        blank=True, help_text="Phone extension", max_length=10
                    ),
                ),
                (
                    "qualifications",
                    models.TextField(
                        blank=True,
                        help_text="Professional qualifications and certifications",
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True,
                        help_text="Digital signature for reports",
                        null=True,
                        upload_to="signatures/",
                    ),
                ),
                (
                    "can_approve_results",
                    models.BooleanField(
                        default=False,
                        help_text="Override: Allow user to approve test results",
                    ),
                ),
                (
                    "can_release_reports",
                    models.BooleanField(
                        default=False,
                        help_text="Override: Allow user to release reports",
                    ),
                ),
                (
                    "is_active_lims",
                    models.BooleanField(
                        default=True, help_text="Whether user can access LIMS features"
                    ),
                ),
                (
                    "login_attempts",
                    models.PositiveIntegerField(
                        default=0, help_text="Failed login attempt count"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, help_text="Account locked due to failed attempts"
                    ),
                ),
                (
                    "last_password_change",
                    models.DateTimeField(
                        blank=True, help_text="Last password change date", null=True
                    ),
                ),
                (
                    "require_password_change",
                    models.BooleanField(
                        default=False, help_text="Force password change on next login"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(
                        blank=True, help_text="Last activity timestamp", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="users.role",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userprofile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lims_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "ordering": ["-last_activity"],
            },
        ),
    ]
