# Generated by Django 6.0.2 on 2026-02-10 19:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorageRack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rack_id", models.CharField(max_length=50)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "shelf_number",
                    models.PositiveIntegerField(
                        blank=True, help_text="Shelf position in unit", null=True
                    ),
                ),
                (
                    "rows",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="Number of rows (A-H typically)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "columns",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Number of columns (1-12 typically)",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "rack_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Box rack', 'Tube rack'",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Storage Rack",
                "verbose_name_plural": "Storage Racks",
                "ordering": ["unit", "shelf_number", "rack_id"],
            },
        ),
        migrations.CreateModel(
            name="StorageUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("FREEZER_MINUS80", "-80°C Freezer"),
                            ("FREEZER_MINUS20", "-20°C Freezer"),
                            ("REFRIGERATOR", "Refrigerator (2-8°C)"),
                            ("NITROGEN_TANK", "Liquid Nitrogen Tank"),
                            ("ROOM_TEMP", "Room Temperature Storage"),
                            ("INCUBATOR", "Incubator"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location (room, floor, building)",
                        max_length=200,
                    ),
                ),
                (
                    "temperature_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum temperature (°C)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "temperature_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum temperature (°C)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "temperature_target",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target temperature (°C)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("FULL", "Full"),
                            ("OUT_OF_SERVICE", "Out of Service"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "capacity_description",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '4 shelves, 20 racks per shelf'",
                        max_length=200,
                    ),
                ),
                ("has_temperature_monitoring", models.BooleanField(default=False)),
                ("has_alarm", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Storage Unit",
                "verbose_name_plural": "Storage Units",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StoragePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Position label (e.g., A1, B2)", max_length=10
                    ),
                ),
                ("row", models.PositiveIntegerField(blank=True, null=True)),
                ("column", models.PositiveIntegerField(blank=True, null=True)),
                ("is_occupied", models.BooleanField(default=False)),
                ("is_reserved", models.BooleanField(default=False)),
                ("stored_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "stored_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stored_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="storage.storagerack",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Position",
                "verbose_name_plural": "Storage Positions",
                "ordering": ["rack", "position"],
                "unique_together": {("rack", "position")},
            },
        ),
        migrations.CreateModel(
            name="StorageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(
                        help_text="Sample identifier (stored for historical reference)",
                        max_length=100,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("STORE", "Sample Stored"),
                            ("RETRIEVE", "Sample Retrieved"),
                            ("MOVE", "Sample Moved"),
                            ("DISPOSE", "Sample Disposed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "from_position",
                    models.CharField(
                        blank=True,
                        help_text="Previous location (for moves)",
                        max_length=100,
                    ),
                ),
                (
                    "to_position",
                    models.CharField(
                        blank=True, help_text="New location (for moves)", max_length=100
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="storage.storageposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Log",
                "verbose_name_plural": "Storage Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="storagerack",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="racks",
                to="storage.storageunit",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storagerack",
            unique_together={("unit", "rack_id")},
        ),
    ]
