# Generated by Django 6.0.2 on 2026-02-15 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab_management", "0021_remove_patient_barcode_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the consent protocol", max_length=255
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version identifier (e.g., '1.0', '2.1', 'A')",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the consent protocol",
                    ),
                ),
                (
                    "protocol_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Research Consent"),
                            ("GENETIC", "Genetic Testing Consent"),
                            ("BIOBANK", "Biobanking Consent"),
                            ("CLINICAL_TRIAL", "Clinical Trial Consent"),
                            ("DATA_SHARING", "Data Sharing Consent"),
                            ("PEDIATRIC", "Pediatric Assent/Consent"),
                            ("EMERGENCY", "Emergency Research Consent"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        help_text="Type of consent protocol",
                        max_length=20,
                    ),
                ),
                (
                    "irb_number",
                    models.CharField(
                        blank=True, help_text="IRB protocol number", max_length=100
                    ),
                ),
                (
                    "irb_approval_date",
                    models.DateField(
                        blank=True, help_text="Date of IRB approval", null=True
                    ),
                ),
                (
                    "irb_expiration_date",
                    models.DateField(
                        blank=True, help_text="Date of IRB expiration", null=True
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when this protocol version becomes effective"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when this protocol version expires (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this protocol is currently active",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        help_text="PDF or document file of the consent form",
                        null=True,
                        upload_to="consent_protocols/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requires_witness",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this consent requires a witness signature",
                    ),
                ),
                (
                    "requires_legal_representative",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this consent can be signed by a legal representative",
                    ),
                ),
                (
                    "minimum_age",
                    models.PositiveIntegerField(
                        default=18, help_text="Minimum age for direct consent"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this protocol",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_consent_protocols",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent Protocol",
                "verbose_name_plural": "Consent Protocols",
                "ordering": ["-effective_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="PatientConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONSENTED", "Consented"),
                            ("DECLINED", "Declined"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        help_text="Current consent status",
                        max_length=20,
                    ),
                ),
                (
                    "consent_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when consent was provided",
                        null=True,
                    ),
                ),
                (
                    "consent_method",
                    models.CharField(
                        choices=[
                            ("IN_PERSON", "In Person"),
                            ("ELECTRONIC", "Electronic Signature"),
                            ("PHONE", "Phone Consent"),
                            ("MAIL", "Written Mail"),
                            ("LAR", "Legally Authorized Representative"),
                        ],
                        default="IN_PERSON",
                        help_text="Method of obtaining consent",
                        max_length=20,
                    ),
                ),
                (
                    "witness_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the witness (if required)",
                        max_length=255,
                    ),
                ),
                (
                    "witness_signature_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time of witness signature",
                        null=True,
                    ),
                ),
                (
                    "representative_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of legally authorized representative (if applicable)",
                        max_length=255,
                    ),
                ),
                (
                    "representative_relationship",
                    models.CharField(
                        blank=True,
                        help_text="Relationship to patient (e.g., Parent, Guardian, POA)",
                        max_length=100,
                    ),
                ),
                (
                    "withdrawal_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time of consent withdrawal",
                        null=True,
                    ),
                ),
                (
                    "withdrawal_reason",
                    models.TextField(
                        blank=True, help_text="Reason for withdrawing consent"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this consent is currently active",
                    ),
                ),
                (
                    "signed_document",
                    models.FileField(
                        blank=True,
                        help_text="Scanned copy of signed consent form",
                        null=True,
                        upload_to="signed_consents/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the consent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consented_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who obtained the consent",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obtained_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        help_text="Patient who provided consent",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to="lab_management.patient",
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        help_text="Consent protocol being consented to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_consents",
                        to="compliance.consentprotocol",
                    ),
                ),
                (
                    "withdrawn_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who processed the withdrawal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Consent",
                "verbose_name_plural": "Patient Consents",
                "ordering": ["-consent_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="consentprotocol",
            index=models.Index(
                fields=["is_active", "effective_date"],
                name="compliance__is_acti_9ca5b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consentprotocol",
            index=models.Index(
                fields=["irb_number"], name="compliance__irb_num_be59fe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="consentprotocol",
            unique_together={("name", "version")},
        ),
        migrations.AddIndex(
            model_name="patientconsent",
            index=models.Index(
                fields=["patient", "status"], name="compliance__patient_c6af1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientconsent",
            index=models.Index(
                fields=["protocol", "status"], name="compliance__protoco_8dff7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientconsent",
            index=models.Index(
                fields=["consent_date"], name="compliance__consent_e07284_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientconsent",
            index=models.Index(
                fields=["is_active"], name="compliance__is_acti_395aa6_idx"
            ),
        ),
    ]
