# Generated by Django 6.0.2 on 2026-04-07 09:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectronicSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="Primary key of the signed record."
                    ),
                ),
                (
                    "record_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of the record state at the moment of signing (for non-repudiation — prevents after-the-fact edits from altering what the signer actually approved).",
                    ),
                ),
                ("signer_username", models.CharField(max_length=150)),
                ("signer_full_name", models.CharField(max_length=300)),
                (
                    "signer_role",
                    models.CharField(
                        blank=True,
                        help_text='Role/title at time of signing (e.g., "Laboratory Director").',
                        max_length=100,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("AUTHORSHIP", "Authorship"),
                            ("REVIEW", "Review"),
                            ("APPROVAL", "Approval"),
                            ("RESPONSIBILITY", "Responsibility"),
                            ("RELEASE", "Release to patient/clinician"),
                            ("AMENDMENT", "Amendment"),
                            ("WITNESS", "Witness"),
                            ("REJECTION", "Rejection"),
                            ("OTHER", "Other (see notes)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "meaning",
                    models.CharField(
                        help_text="Free-text meaning of the signature, as displayed to the signer at the moment of signing (21 CFR 11.50).",
                        max_length=500,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("PASSWORD", "Username + password re-authentication"),
                            ("BIOMETRIC", "Biometric"),
                            ("SMARTCARD", "Smart card / PKI"),
                            ("MFA", "Multi-factor authentication"),
                        ],
                        default="PASSWORD",
                        max_length=20,
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("integrity_hash", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Model of the signed record.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="electronic_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Electronic Signature",
                "verbose_name_plural": "Electronic Signatures",
                "ordering": ["-signed_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-signed_at"],
                        name="compliance__content_f1fc8e_idx",
                    ),
                    models.Index(
                        fields=["signer", "-signed_at"],
                        name="compliance__signer__8ebba9_idx",
                    ),
                ],
            },
        ),
    ]
