# Generated by Django 6.0.2 on 2026-02-15 09:12

import django.db.models.deletion
import django.utils.timezone
import qms.models.documents
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenants", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#3182ce", help_text="Hex color code", max_length=7
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Document Tag",
                "verbose_name_plural": "Document Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "prefix",
                    models.CharField(
                        blank=True, help_text="Document numbering prefix", max_length=10
                    ),
                ),
                (
                    "review_interval_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Default review interval for documents in this category",
                    ),
                ),
                ("requires_approval", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="qms.documentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Category",
                "verbose_name_plural": "Document Categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="DocumentFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "folder_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique folder identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_private", models.BooleanField(default=False)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowed_groups",
                    models.ManyToManyField(
                        blank=True, related_name="accessible_folders", to="auth.group"
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_folders",
                        to="tenants.laboratory",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="qms.documentfolder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Folder",
                "verbose_name_plural": "Document Folders",
                "ordering": ["sequence", "name"],
                "unique_together": {("laboratory", "parent", "name")},
            },
        ),
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "content",
                    models.TextField(help_text="Template content with placeholders"),
                ),
                (
                    "editor_type",
                    models.CharField(
                        choices=[
                            ("RICHTEXT", "Rich Text"),
                            ("MARKDOWN", "Markdown"),
                            ("HTML", "HTML"),
                        ],
                        default="RICHTEXT",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="qms.documentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Template",
                "verbose_name_plural": "Document Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique document identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "document_number",
                    models.CharField(
                        blank=True, help_text="Official document number", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "editor_type",
                    models.CharField(
                        choices=[
                            ("RICHTEXT", "Rich Text"),
                            ("MARKDOWN", "Markdown"),
                            ("HTML", "HTML"),
                            ("PDF", "PDF Upload"),
                            ("EXTERNAL", "External Link"),
                        ],
                        default="RICHTEXT",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Accessible to all laboratory members"
                    ),
                ),
                (
                    "review_interval_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("external_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("archived_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="authored_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenants.laboratory",
                    ),
                ),
                (
                    "readers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users with explicit read access",
                        related_name="readable_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_documents",
                    models.ManyToManyField(
                        blank=True, help_text="Related documents", to="qms.document"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="qms.documentcategory",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="qms.documentfolder",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="documents", to="qms.documenttag"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="qms.documenttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-updated_at"],
                "unique_together": {("laboratory", "document_number")},
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(help_text="e.g., 1.0, 1.1, 2.0", max_length=20),
                ),
                ("is_major_version", models.BooleanField(default=False)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text="Document content (for text-based documents)",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=qms.models.documents.document_file_path,
                    ),
                ),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                (
                    "change_summary",
                    models.TextField(
                        blank=True, help_text="Summary of changes in this version"
                    ),
                ),
                ("word_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "checksum",
                    models.CharField(
                        blank=True, help_text="SHA-256 checksum", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="qms.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Version",
                "verbose_name_plural": "Document Versions",
                "ordering": ["-created_at"],
                "unique_together": {("document", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="DocumentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("SUPERSEDED", "Superseded"),
                            ("ARCHIVED", "Archived"),
                            ("REJECTED", "Rejected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("comment", models.TextField(blank=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="qms.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_history",
                        to="qms.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Status",
                "verbose_name_plural": "Document Statuses",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DocumentReviewCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_cycles",
                        to="qms.document",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_cycles",
                        to="qms.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Review Cycle",
                "verbose_name_plural": "Document Review Cycles",
                "ordering": ["-initiated_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("line_number", models.PositiveIntegerField(blank=True, null=True)),
                ("selected_text", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="qms.document",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="qms.documentcomment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to="qms.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Comment",
                "verbose_name_plural": "Document Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentReviewStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(default=1)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Technical Reviewer, QA Manager",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("signature_hash", models.CharField(blank=True, max_length=64)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="qms.documentreviewcycle",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Review Step",
                "verbose_name_plural": "Document Review Steps",
                "ordering": ["review_cycle", "sequence"],
                "unique_together": {("review_cycle", "reviewer")},
            },
        ),
        migrations.CreateModel(
            name="DocumentSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notify_on",
                    models.CharField(
                        choices=[
                            ("ALL", "All Changes"),
                            ("STATUS", "Status Changes Only"),
                            ("VERSION", "New Versions Only"),
                            ("REVIEW", "Review Requests Only"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="qms.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Subscription",
                "verbose_name_plural": "Document Subscriptions",
                "unique_together": {("document", "user")},
            },
        ),
        migrations.CreateModel(
            name="DocumentAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEWED", "Viewed"),
                            ("DOWNLOADED", "Downloaded"),
                            ("PRINTED", "Printed"),
                            ("CREATED", "Created"),
                            ("EDITED", "Edited"),
                            ("VERSION_CREATED", "Version Created"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("SHARED", "Shared"),
                            ("COMMENTED", "Commented"),
                            ("REVIEWED", "Reviewed"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                            ("RESTORED", "Restored"),
                            ("DELETED", "Deleted"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_trail",
                        to="qms.document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_trail",
                        to="qms.documentversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Audit",
                "verbose_name_plural": "Document Audits",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["document", "-timestamp"],
                        name="qms_documen_documen_a8e50d_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="qms_documen_user_id_1c39bf_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="qms_documen_action_7a3050_idx",
                    ),
                ],
            },
        ),
    ]
