# Generated by Django 5.1.4 on 2024-12-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_management', '0011_patient_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReagentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=5)),
                ('supplier', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagents.reagentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ReagentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField()),
                ('usage_date', models.DateField(auto_now_add=True)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reagents.reagent')),
                ('used_in_lab_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_management.laborder')),
            ],
        ),
    ]
