# Generated by Django 5.1.4 on 2024-12-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reagent',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='reagent',
            name='reorder_level',
        ),
        migrations.RemoveField(
            model_name='reagent',
            name='supplier',
        ),
        migrations.AddField(
            model_name='reagent',
            name='item_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='lot_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='on_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reagent',
            name='opening_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='received_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='vendor',
            field=models.CharField(blank=True, choices=[('BIG', 'BIG'), ('SMALL', 'SMALL')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='category',
            field=models.CharField(choices=[('BIOASSAY_SNIBE', 'BIOASSAY SNIBE'), ('MAGLUMI_SNIBE', 'MAGLUMI SNIBE'), ('BIG', 'BIG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='quantity_in_stock',
            field=models.IntegerField(),
        ),
    ]
