# Generated by Django 6.0.2 on 2026-02-10 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("molecular_diagnostics", "0001_initial"),
        ("reagents", "0002_remove_reagent_date_added_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MolecularReagent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("catalog_number", models.CharField(blank=True, max_length=100)),
                ("lot_number", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PRIMER", "Primer"),
                            ("PROBE", "Probe"),
                            ("ENZYME_KIT", "Enzyme Kit"),
                            ("LIBRARY_PREP", "Library Prep Kit"),
                            ("EXTRACTION_KIT", "Extraction Kit"),
                            ("MASTER_MIX", "Master Mix"),
                            ("INDEX_KIT", "Index/Barcode Kit"),
                            ("CONTROL", "Control Material"),
                            ("BUFFER", "Buffer/Solution"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                (
                    "sequence",
                    models.CharField(
                        blank=True,
                        help_text="Nucleotide sequence (for primers/probes)",
                        max_length=500,
                    ),
                ),
                (
                    "tm_celsius",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Melting temperature in °C",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "gc_content",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="GC content percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "modification_5prime",
                    models.CharField(
                        blank=True,
                        help_text="5' modification (e.g., FAM, HEX)",
                        max_length=100,
                    ),
                ),
                (
                    "modification_3prime",
                    models.CharField(
                        blank=True,
                        help_text="3' modification (e.g., BHQ1, TAMRA)",
                        max_length=100,
                    ),
                ),
                (
                    "concentration",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "concentration_unit",
                    models.CharField(
                        blank=True, help_text="e.g., µM, ng/µL, Units/µL", max_length=20
                    ),
                ),
                (
                    "storage_temperature",
                    models.CharField(
                        choices=[
                            ("MINUS80", "-80°C"),
                            ("MINUS20", "-20°C"),
                            ("REFRIGERATED", "2-8°C"),
                            ("ROOM_TEMP", "Room Temperature"),
                        ],
                        default="MINUS20",
                        max_length=20,
                    ),
                ),
                ("storage_location", models.CharField(blank=True, max_length=200)),
                (
                    "initial_volume_ul",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Initial volume in µL",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_volume_ul",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Current remaining volume in µL",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "reactions_per_kit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of reactions (for kits)",
                        null=True,
                    ),
                ),
                (
                    "reactions_remaining",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("received_date", models.DateField(default=django.utils.timezone.now)),
                ("opened_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField()),
                (
                    "stability_after_opening_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Days stable after opening", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Has this reagent been validated for use?",
                    ),
                ),
                ("validation_date", models.DateField(blank=True, null=True)),
                ("validation_notes", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_gene_targets",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Gene targets this reagent is used for",
                        related_name="reagents",
                        to="molecular_diagnostics.genetarget",
                    ),
                ),
                (
                    "linked_test_panels",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reagents",
                        to="molecular_diagnostics.moleculartestpanel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Molecular Reagent",
                "verbose_name_plural": "Molecular Reagents",
                "ordering": ["name"],
            },
        ),
    ]
