# Generated by Django 6.0.2 on 2026-02-15 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for the organization",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                (
                    "subscription_tier",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("BASIC", "Basic"),
                            ("PROFESSIONAL", "Professional"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="FREE",
                        max_length=20,
                    ),
                ),
                ("max_laboratories", models.PositiveIntegerField(default=1)),
                ("max_users", models.PositiveIntegerField(default=10)),
                ("max_samples_per_month", models.PositiveIntegerField(default=1000)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Laboratory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code for the laboratory", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "lab_type",
                    models.CharField(
                        choices=[
                            ("CLINICAL", "Clinical Laboratory"),
                            ("RESEARCH", "Research Laboratory"),
                            ("MOLECULAR", "Molecular Diagnostics"),
                            ("PATHOLOGY", "Pathology"),
                            ("MICROBIOLOGY", "Microbiology"),
                            ("BIOBANK", "Biobank"),
                            ("GENOMICS", "Genomics"),
                            ("OTHER", "Other"),
                        ],
                        default="CLINICAL",
                        max_length=50,
                    ),
                ),
                ("accreditation_number", models.CharField(blank=True, max_length=100)),
                ("accreditation_body", models.CharField(blank=True, max_length=255)),
                ("accreditation_expiry", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "features_enabled",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Feature flags for this laboratory",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratories",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratory",
                "verbose_name_plural": "Laboratories",
                "ordering": ["organization", "name"],
                "unique_together": {("organization", "code")},
            },
        ),
        migrations.CreateModel(
            name="LaboratoryMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("LAB_DIRECTOR", "Laboratory Director"),
                            ("LAB_MANAGER", "Laboratory Manager"),
                            ("SUPERVISOR", "Supervisor"),
                            ("SENIOR_TECHNICIAN", "Senior Technician"),
                            ("TECHNICIAN", "Technician"),
                            ("TRAINEE", "Trainee"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="TECHNICIAN",
                        max_length=50,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, help_text="Default laboratory for this user"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.laboratory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratory_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Laboratory Membership",
                "verbose_name_plural": "Laboratory Memberships",
                "unique_together": {("user", "laboratory")},
            },
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Administrator"),
                            ("MANAGER", "Manager"),
                            ("MEMBER", "Member"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="MEMBER",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="tenants.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Membership",
                "verbose_name_plural": "Organization Memberships",
                "unique_together": {("user", "organization")},
            },
        ),
    ]
