# Generated by Django 6.0.2 on 2026-02-10 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                (
                    "maintenance_interval_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Recommended maintenance interval in days",
                        null=True,
                    ),
                ),
                (
                    "calibration_interval_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Required calibration interval in days",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Instrument Type",
                "verbose_name_plural": "Instrument Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("asset_number", models.CharField(blank=True, max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                ("software_version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("CALIBRATION", "Under Calibration"),
                            ("REPAIR", "Under Repair"),
                            ("RETIRED", "Retired"),
                            ("OUT_OF_SERVICE", "Out of Service"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location in the lab",
                        max_length=200,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("warranty_expiration", models.DateField(blank=True, null=True)),
                ("installation_date", models.DateField(blank=True, null=True)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                ("last_calibration", models.DateField(blank=True, null=True)),
                ("next_calibration", models.DateField(blank=True, null=True)),
                ("contact_person", models.CharField(blank=True, max_length=200)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True)),
                (
                    "specifications",
                    models.JSONField(
                        blank=True, default=dict, help_text="Technical specifications"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instruments",
                        to="equipment.instrumenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument",
                "verbose_name_plural": "Instruments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("PREVENTIVE", "Preventive Maintenance"),
                            ("CORRECTIVE", "Corrective Maintenance"),
                            ("CALIBRATION", "Calibration"),
                            ("QUALIFICATION", "Qualification (IQ/OQ/PQ)"),
                            ("REPAIR", "Repair"),
                            ("UPGRADE", "Upgrade"),
                            ("INSPECTION", "Inspection"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("performed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "performed_by",
                    models.CharField(
                        blank=True,
                        help_text="Name of technician/engineer",
                        max_length=200,
                    ),
                ),
                (
                    "service_provider",
                    models.CharField(
                        blank=True, help_text="External service company", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of work performed"
                    ),
                ),
                (
                    "findings",
                    models.TextField(
                        blank=True, help_text="Issues found during maintenance"
                    ),
                ),
                (
                    "actions_taken",
                    models.TextField(
                        blank=True, help_text="Corrective actions performed"
                    ),
                ),
                (
                    "parts_replaced",
                    models.TextField(blank=True, help_text="List of replaced parts"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "next_due",
                    models.DateField(
                        blank=True,
                        help_text="Next maintenance/calibration due date",
                        null=True,
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        blank=True,
                        help_text="Calibration certificate or maintenance report",
                        null=True,
                        upload_to="maintenance_certificates/%Y/%m/",
                    ),
                ),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                (
                    "passed",
                    models.BooleanField(
                        blank=True,
                        help_text="Did the instrument pass calibration/qualification?",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="equipment.instrument",
                    ),
                ),
                (
                    "performed_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Record",
                "verbose_name_plural": "Maintenance Records",
                "ordering": ["-scheduled_date"],
            },
        ),
    ]
