# Generated by Django 5.1.4 on 2024-12-11 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='report',
            name='test',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='test',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='civil_id',
            new_name='OP_NO',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='mobile_number',
            new_name='phone_no',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='clinical_history',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='doc_fee',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='resident_card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tribe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('sample_type', models.CharField(choices=[('Hematology', 'Hematology'), ('Microbiology', 'Microbiology'), ('Urine Routine Examination', 'Urine Routine Examination'), ('EDTA Blood', 'EDTA Blood'), ('Stool', 'Stool')], max_length=100)),
                ('sample_collected', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_management.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.TextField()),
                ('result_updated', models.BooleanField(default=False)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_management.laborder')),
            ],
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
