# Generated by Django 5.1.4 on 2024-12-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0002_remove_report_patient_remove_report_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=50),
        ),
    ]
