# Generated by Django 5.1.4 on 2024-12-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0003_alter_patient_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
