# Generated by Django 5.1.4 on 2024-12-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0004_patient_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doc_fee',
        ),
        migrations.AddField(
            model_name='patient',
            name='barcode_image_url',
            field=models.URLField(default='unknown'),
            preserve_default=False,
        ),
    ]
