# Generated by Django 5.1.4 on 2024-12-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0005_remove_patient_doc_fee_patient_barcode_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='barcode_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
