# Generated by Django 5.1.4 on 2024-12-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0006_alter_patient_barcode_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='barcode',
        ),
    ]
