# Generated by Django 5.1.4 on 2024-12-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0007_remove_patient_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='sample_insufficient',
            field=models.BooleanField(default=False),
        ),
    ]
