# Generated by Django 5.1.4 on 2024-12-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0008_laborder_sample_insufficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='sample_type',
            field=models.CharField(choices=[('TORCH', 'TORCH'), ('Stool', 'Stool'), ('Retrovirology', 'Retrovirology'), ('Clinical Pathology', 'Clinical Pathology'), ('Tumour Markers', 'Tumour Markers'), ('Hormones', 'Hormones'), ('Anti Allergy', 'Anti Allergy'), ('Hepatitis', 'Hepatitis'), ('Special Tests', 'Special Tests'), ('Microbiology', 'Microbiology'), ('Pathology', 'Pathology'), ('Serology', 'Serology'), ('Haematology', 'Haematology'), ('Biochemistry', 'Biochemistry'), ('Physical & Chemical Examination', 'Physical & Chemical Examination'), ('Urine Routine Examination', 'Urine Routine Examination'), ('Semen', 'Semen'), ('Culture & Sensitivity', 'Culture & Sensitivity'), ('EDTA Blood', 'EDTA Blood'), ('Serum', 'Serum'), ('Blood', 'Blood'), ('Serum/Blood', 'Serum/Blood'), ('Urine', 'Urine'), ('Urn', 'Urn'), ('Plasma, Serum, Urine', 'Plasma, Serum, Urine'), ('Urine Culture', 'Urine Culture'), ('Citrate Plasma', 'Citrate Plasma'), ('CBC', 'CBC')], max_length=100),
        ),
    ]
