# Generated by Django 5.1.4 on 2024-12-14 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0009_alter_laborder_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
