# Generated by Django 5.1.4 on 2024-12-15 10:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0010_laborder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
