# Generated by Django 5.1.4 on 2024-12-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0013_alter_laborder_sample_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='clinic_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='client_name',
            field=models.CharField(blank=True, choices=[('Al Farooq Mabela', 'Al Farooq Mabela'), ('Adlife', 'Adlife'), ('Advance Medical Center', 'Advance Medical Center'), ('Afaq Healthcare', 'Afaq Healthcare'), ('Afaq Visa Medical', 'Afaq Visa Medical'), ('Al Amal', 'Al Amal'), ('Al Farooq Barka', 'Al Farooq Barka'), ('Al Farooq Sawadi', 'Al Farooq Sawadi'), ('Al Manar', 'Al Manar'), ('Al Manar Visa Medical', 'Al Manar Visa Medical'), ('Al Rafadian', 'Al Rafadian'), ('Al Saada', 'Al Saada'), ('Al Shammar Polyclinic', 'Al Shammar Polyclinic'), ('Ava Labs', 'Ava Labs'), ('Azad Healthcare', 'Azad Healthcare'), ('Azad Healthcare Visa Medical', 'Azad Healthcare Visa Medical'), ('Bahwan', 'Bahwan'), ('Barakath Al Noor Clinic', 'Barakath Al Noor Clinic'), ('Best Medicare', 'Best Medicare'), ('Clinica Victoria', 'Clinica Victoria'), ('Clinicare', 'Clinicare'), ('Crystal Clinic Visa Medical', 'Crystal Clinic Visa Medical'), ('Crystal Polyclinic', 'Crystal Polyclinic'), ('El Abda', 'El Abda'), ('Fajr Al Madina', 'Fajr Al Madina'), ('Fusion', 'Fusion')], max_length=100, null=True),
        ),
    ]
