# Generated by Django 5.1.4 on 2024-12-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0015_laborder_container_alter_laborder_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='test_type',
            field=models.CharField(blank=True, choices=[('HORMONES_AND_VITAMINS', 'Hormones And Vitamins'), ('IMMUNOLOGY', 'Immunology'), ('SEROLOGY', 'Serology'), ('CANCER_MARKERS', 'CANCER MARKERS'), ('MICROBIOLOGY_ROUTINE', 'Microbiology Routine'), ('MICROBIOLOGY_CULTURE', 'Microbiology Culture')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='sample_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='test_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
