# Generated by Django 5.1.4 on 2024-12-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0016_laborder_test_type_alter_laborder_sample_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='sample_type',
            field=models.CharField(choices=[('SERUM', 'SERUM'), ('STOOL', 'STOOL'), ('BLOOD', 'BLOOD'), ('URINE', 'URINE'), ('SEMEN', 'SEMEN'), ('SPUTUM', 'SPUTUM'), ('EDTA BLOOD', 'EDTA BLOOD'), ('HIGH VAGINAL SWAB', 'HIGH VAGINAL SWAB'), ('NASAL SWAB', 'NASAL SWAB'), ('BIOPSY', 'BIOPSY'), ('SALIVA', 'SALIVA'), ('CEREBROSPINAL FLUID', 'CEREBROSPINAL FLUID')], max_length=100),
        ),
    ]
