# Generated by Django 5.1.4 on 2024-12-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0017_alter_laborder_sample_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laborder',
            options={'verbose_name': 'Lab Order', 'verbose_name_plural': 'Lab Orders'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Test Result', 'verbose_name_plural': 'Test Results'},
        ),
    ]
