# Generated by Django 5.1.4 on 2024-12-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0018_alter_laborder_options_alter_testresult_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='test_type',
            field=models.CharField(blank=True, choices=[('HORMONES_AND_VITAMINS', 'Hormones And Vitamins'), ('IMMUNOLOGY', 'Immunology'), ('SEROLOGY', 'Serology'), ('CANCER_MARKERS', 'CANCER MARKERS'), ('MICROBIOLOGY_ROUTINE', 'Microbiology Routine'), ('MICROBIOLOGY_CULTURE', 'Microbiology Culture'), ('BIOCHEMISTRY', 'Biochemistry')], max_length=50, null=True),
        ),
    ]
