# Generated by Django 5.1.4 on 2024-12-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0019_alter_laborder_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='test_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
