# Generated by Django 5.1.4 on 2024-12-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_management', '0020_laborder_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='barcode_image_url',
        ),
        migrations.AddField(
            model_name='patient',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='test_name',
            field=models.CharField(blank=True, choices=[('ANTI MULLERIAN HORMONE', 'ANTI MULLERIAN HORMONE'), ('B-HCG IN BLOOD', 'B-HCG IN BLOOD'), ('CORTISOL', 'CORTISOL'), ('DHEA - S', 'DHEA - S'), ('ESTRADIOL', 'ESTRADIOL'), ('FREE T3', 'FREE T3'), ('FREE T4', 'FREE T4'), ('FSH', 'FSH'), ('LH', 'LH'), ('PROGESTERONE (FREE)', 'PROGESTERONE (FREE)'), ('PROGESTERONE (TOTAL)', 'PROGESTERONE (TOTAL)'), ('PROLACTIN', 'PROLACTIN'), ('SEX HORMONE BINDING GLOBULIN(SHBG)', 'SEX HORMONE BINDING GLOBULIN(SHBG)'), ('TESTOSTERONE FREE', 'TESTOSTERONE FREE'), ('TESTOSTERONE TOTAL', 'TESTOSTERONE TOTAL'), ('THYROID STIMULATINGHORMONE (TSH)', 'THYROID STIMULATINGHORMONE (TSH)'), ('VITAMIN B12', 'VITAMIN B12'), ('VITAMIN D3', 'VITAMIN D3'), ('INSULIN', 'INSULIN'), ('PREGNANCY TEST (BLOOD)', 'PREGNANCY TEST (BLOOD)'), ('PREGNANCY TEST (SERUM)', 'PREGNANCY TEST (SERUM)'), ('PREGNANCY TEST (URINE)', 'PREGNANCY TEST (URINE)'), ('THYROID PEROXIDASEAUTOANTIBODIES (ATPO)', 'THYROID PEROXIDASEAUTOANTIBODIES (ATPO)'), ('VITAMIN B9 (FOLIC ACID)', 'VITAMIN B9 (FOLIC ACID)'), ('ALBUMIN', 'ALBUMIN'), ('ALKALINE PHOSPHATASE', 'ALKALINE PHOSPHATASE'), ('AMYLASE', 'AMYLASE'), ('BILIRUBIN (direct)', 'BILIRUBIN (direct)'), ('BILIRUBIN (indirect)', 'BILIRUBIN (indirect)'), ('BILIRUBIN (total)', 'BILIRUBIN (total)'), ('CALCIUM (total)', 'CALCIUM (total)'), ('CALCIUM (CORRECTED)', 'CALCIUM (CORRECTED)'), ('Sodium', 'Sodium'), ('Potassium', 'Potassium'), ('Chloride', 'Chloride'), ('CHOLESTEROL', 'CHOLESTEROL'), ('CREATININE', 'CREATININE'), ('CK, TOTAL', 'CK, TOTAL'), ('CK MB', 'CK MB'), ('GLUCOSE (FASTING)', 'GLUCOSE (FASTING)'), ('GLUCOSE (P.P)', 'GLUCOSE (P.P)'), ('GLUCOSE (RANDOM)', 'GLUCOSE (RANDOM)'), ('HDL', 'HDL'), ('IRON', 'IRON'), ('LDH', 'LDH'), ('LDL', 'LDL'), ('LIPASE', 'LIPASE'), ('MAGNESIUM', 'MAGNESIUM'), ('PHOSPHORUS', 'PHOSPHORUS'), ('SGOT(AST)', 'SGOT(AST)'), ('SGPT(ALT)', 'SGPT(ALT)'), ('TOTAL PROTEIN', 'TOTAL PROTEIN'), ('TRIGLYCERIDE', 'TRIGLYCERIDE'), ('UREA', 'UREA'), ('URIC ACID', 'URIC ACID'), ('ZINC', 'ZINC'), ('CRP H.S', 'CRP H.S'), ('MONOSPOT', 'MONOSPOT'), ('RHEUMATOID FACTOR', 'RHEUMATOID FACTOR'), ('SYPHILIS', 'SYPHILIS'), ('CA-125', 'CA-125'), ('PSA TOTAL', 'PSA TOTAL'), ('PSA FREE', 'PSA FREE'), ('TB GOLD QUANTIFERON', 'TB GOLD QUANTIFERON'), ('BLOOD CULTURE ANDSENSITIVITY', 'BLOOD CULTURE ANDSENSITIVITY'), ('SPUTUM CULTURE &SENSITIVITY', 'SPUTUM CULTURE &SENSITIVITY'), ('SEMEN CULTURE &SENSITIVITY', 'SEMEN CULTURE &SENSITIVITY'), ('STOOL CULTURE ANDSENSITIVITY', 'STOOL CULTURE ANDSENSITIVITY'), ('VAGINAL SWAB CULTURE &SENSITIVITY', 'VAGINAL SWAB CULTURE &SENSITIVITY')], max_length=100),
        ),
    ]
