# Generated by Django 6.0.2 on 2026-02-10 19:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("lab_management", "0021_remove_patient_barcode_image_url_and_more"),
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "symbol",
                    models.CharField(
                        help_text="Official gene symbol (e.g., BRCA1, TP53)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("chromosome", models.CharField(blank=True, max_length=10)),
                (
                    "genomic_coordinates",
                    models.CharField(
                        blank=True,
                        help_text="e.g., chr17:43044295-43170245",
                        max_length=200,
                    ),
                ),
                (
                    "transcript_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference transcript (e.g., NM_007294.4)",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "clinical_significance",
                    models.TextField(
                        blank=True, help_text="Clinical relevance of this gene"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Gene Target",
                "verbose_name_plural": "Gene Targets",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="MolecularSampleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("collection_instructions", models.TextField(blank=True)),
                (
                    "storage_temperature",
                    models.CharField(
                        blank=True,
                        help_text="e.g., -20°C, 2-8°C, Room Temperature",
                        max_length=50,
                    ),
                ),
                (
                    "stability_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum hours sample remains stable at storage temperature",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Molecular Sample Type",
                "verbose_name_plural": "Molecular Sample Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NGSLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("library_id", models.CharField(max_length=50, unique=True)),
                (
                    "index_sequence",
                    models.CharField(help_text="Index/barcode sequence", max_length=50),
                ),
                (
                    "index_name",
                    models.CharField(
                        blank=True, help_text="Index kit name/ID", max_length=100
                    ),
                ),
                (
                    "concentration_ng_ul",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "fragment_size_bp",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Average fragment size in base pairs",
                        null=True,
                    ),
                ),
                (
                    "molarity_nm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Library molarity in nM",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("prep_date", models.DateField(default=django.utils.timezone.now)),
                ("qc_passed", models.BooleanField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "NGS Library",
                "verbose_name_plural": "NGS Libraries",
                "ordering": ["-prep_date"],
            },
        ),
        migrations.CreateModel(
            name="NGSPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pool_id", models.CharField(max_length=50, unique=True)),
                (
                    "concentration_ng_ul",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "molarity_nm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "volume_ul",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pool_date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "NGS Pool",
                "verbose_name_plural": "NGS Pools",
                "ordering": ["-pool_date"],
            },
        ),
        migrations.CreateModel(
            name="PCRPlate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=100, unique=True)),
                (
                    "plate_type",
                    models.CharField(
                        choices=[("96", "96-well"), ("384", "384-well")],
                        default="96",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "PCR Plate",
                "verbose_name_plural": "PCR Plates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PCRResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ct_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cycle threshold value",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "is_detected",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DETECTED", "Detected"),
                            ("NOT_DETECTED", "Not Detected"),
                            ("INDETERMINATE", "Indeterminate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Quantified value (copies/mL, IU/mL, etc.)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("quantity_unit", models.CharField(blank=True, max_length=50)),
                ("fluorescence_channel", models.CharField(blank=True, max_length=50)),
                (
                    "amplification_curve",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Amplification curve data points",
                    ),
                ),
                ("replicate_number", models.PositiveIntegerField(default=1)),
                ("well_position", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "verbose_name": "PCR Result",
                "verbose_name_plural": "PCR Results",
                "ordering": ["molecular_result", "target_gene"],
            },
        ),
        migrations.CreateModel(
            name="PlateWell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Well position (e.g., A1, H12)", max_length=4
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Sample"),
                            ("POSITIVE", "Positive Control"),
                            ("NEGATIVE", "Negative Control"),
                            ("NTC", "No Template Control"),
                            ("CALIBRATOR", "Calibrator"),
                            ("EMPTY", "Empty"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "replicate_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Replicate number for duplicate/triplicate testing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plate Well",
                "verbose_name_plural": "Plate Wells",
                "ordering": ["plate", "position"],
            },
        ),
        migrations.CreateModel(
            name="QCMetricDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("NUMERIC", "Numeric"),
                            ("PERCENTAGE", "Percentage"),
                            ("BOOLEAN", "Pass/Fail"),
                            ("RANGE", "Within Range"),
                        ],
                        default="NUMERIC",
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "min_acceptable",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Minimum acceptable value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "max_acceptable",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Maximum acceptable value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Target/optimal value",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "warning_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Warning threshold (lower)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "warning_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Warning threshold (upper)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "applicable_test_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of test types this metric applies to",
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="If true, failure of this metric fails the entire QC",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "QC Metric Definition",
                "verbose_name_plural": "QC Metric Definitions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QCRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "value_text",
                    models.CharField(
                        blank=True, help_text="For non-numeric results", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("WARNING", "Passed with Warnings"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("passed", models.BooleanField(blank=True, null=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "QC Record",
                "verbose_name_plural": "QC Records",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="SampleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        help_text="Previous status (blank if initial)",
                        max_length=20,
                    ),
                ),
                ("to_status", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("qc_passed", models.BooleanField(blank=True, null=True)),
                ("qc_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Sample History",
                "verbose_name_plural": "Sample Histories",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SequencingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_reads", models.BigIntegerField(blank=True, null=True)),
                ("mapped_reads", models.BigIntegerField(blank=True, null=True)),
                (
                    "mean_coverage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "coverage_uniformity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of target covered at minimum depth",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mean quality score (Phred)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "q30_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of bases >= Q30",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "on_target_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "duplicate_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "trace_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("sequence_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "run_file",
                    models.FileField(
                        blank=True,
                        help_text="Raw data file (FASTQ, BAM, etc.)",
                        null=True,
                        upload_to="sequencing_data/%Y/%m/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sequencing Result",
                "verbose_name_plural": "Sequencing Results",
            },
        ),
        migrations.CreateModel(
            name="VariantCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chromosome", models.CharField(max_length=10)),
                ("position", models.BigIntegerField()),
                ("ref_allele", models.CharField(max_length=500)),
                ("alt_allele", models.CharField(max_length=500)),
                (
                    "hgvs_c",
                    models.CharField(
                        blank=True,
                        help_text="cDNA notation (e.g., c.1234A>G)",
                        max_length=200,
                    ),
                ),
                (
                    "hgvs_p",
                    models.CharField(
                        blank=True,
                        help_text="Protein notation (e.g., p.Arg123Gly)",
                        max_length=200,
                    ),
                ),
                (
                    "variant_type",
                    models.CharField(
                        blank=True,
                        help_text="SNV, Insertion, Deletion, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "consequence",
                    models.CharField(
                        blank=True,
                        help_text="Functional consequence (missense, frameshift, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PATHOGENIC", "Pathogenic"),
                            ("LIKELY_PATHOGENIC", "Likely Pathogenic"),
                            ("VUS", "Variant of Uncertain Significance"),
                            ("LIKELY_BENIGN", "Likely Benign"),
                            ("BENIGN", "Benign"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "zygosity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HETEROZYGOUS", "Heterozygous"),
                            ("HOMOZYGOUS", "Homozygous"),
                            ("HEMIZYGOUS", "Hemizygous"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "allele_frequency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Variant allele frequency in sample",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("read_depth", models.PositiveIntegerField(blank=True, null=True)),
                ("dbsnp_id", models.CharField(blank=True, max_length=50)),
                ("clinvar_id", models.CharField(blank=True, max_length=50)),
                ("cosmic_id", models.CharField(blank=True, max_length=50)),
                (
                    "population_frequency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Population allele frequency (gnomAD, etc.)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "is_reportable",
                    models.BooleanField(
                        default=True, help_text="Include in clinical report"
                    ),
                ),
                ("interpretation", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Variant Call",
                "verbose_name_plural": "Variant Calls",
                "ordering": ["chromosome", "position"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Workflow Definition",
                "verbose_name_plural": "Workflow Definitions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "status_on_entry",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("EXTRACTED", "Extracted"),
                            ("AMPLIFIED", "Amplified"),
                            ("SEQUENCED", "Sequenced"),
                            ("ANALYZED", "Analyzed"),
                            ("REPORTED", "Reported"),
                        ],
                        help_text="Sample status when entering this step",
                        max_length=20,
                    ),
                ),
                (
                    "requires_qc",
                    models.BooleanField(
                        default=False,
                        help_text="Does this step require QC check before proceeding?",
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated time to complete this step",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "is_terminal",
                    models.BooleanField(
                        default=False,
                        help_text="Is this a terminal step (no further transitions)?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Step",
                "verbose_name_plural": "Workflow Steps",
                "ordering": ["workflow", "order"],
            },
        ),
        migrations.CreateModel(
            name="ControlSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "Positive Control"),
                            ("NEGATIVE", "Negative Control"),
                            ("NTC", "No Template Control"),
                            ("CALIBRATOR", "Calibrator"),
                            ("REFERENCE", "Reference Material"),
                        ],
                        max_length=20,
                    ),
                ),
                ("lot_number", models.CharField(blank=True, max_length=50)),
                (
                    "expected_result",
                    models.CharField(
                        help_text="Expected result for this control", max_length=200
                    ),
                ),
                (
                    "expected_value_min",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "expected_value_max",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("storage_temperature", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "target_gene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="control_samples",
                        to="molecular_diagnostics.genetarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control Sample",
                "verbose_name_plural": "Control Samples",
                "ordering": ["control_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="InstrumentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("run_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("protocol_name", models.CharField(blank=True, max_length=200)),
                ("protocol_version", models.CharField(blank=True, max_length=50)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "run_parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Instrument-specific run parameters",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="equipment.instrument",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instrument_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument Run",
                "verbose_name_plural": "Instrument Runs",
                "ordering": ["-run_date"],
            },
        ),
        migrations.CreateModel(
            name="MolecularSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique sample identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "workflow_status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("EXTRACTED", "Extracted"),
                            ("AMPLIFIED", "Amplified"),
                            ("SEQUENCED", "Sequenced"),
                            ("ANALYZED", "Analyzed"),
                            ("REPORTED", "Reported"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "collection_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the sample was collected from the patient",
                        null=True,
                    ),
                ),
                (
                    "received_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the sample was received in the lab",
                    ),
                ),
                (
                    "aliquot_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Aliquot number (1, 2, 3, etc.)",
                        null=True,
                    ),
                ),
                (
                    "volume_ul",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Volume in microliters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "concentration_ng_ul",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Concentration in ng/µL (after extraction)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "a260_280_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="A260/A280 purity ratio",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "aliquot_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent sample if this is an aliquot",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliquots",
                        to="molecular_diagnostics.molecularsample",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_molecular_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="molecular_samples",
                        to="lab_management.laborder",
                    ),
                ),
                (
                    "storage_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="samples",
                        to="storage.storageposition",
                    ),
                ),
                (
                    "sample_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="samples",
                        to="molecular_diagnostics.molecularsampletype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Molecular Sample",
                "verbose_name_plural": "Molecular Samples",
                "ordering": ["-received_datetime"],
            },
        ),
        migrations.CreateModel(
            name="MolecularResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PRELIMINARY", "Preliminary"),
                            ("FINAL", "Final"),
                            ("AMENDED", "Amended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "interpretation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("POSITIVE", "Positive"),
                            ("NEGATIVE", "Negative"),
                            ("INDETERMINATE", "Indeterminate"),
                            ("NOT_TESTED", "Not Tested"),
                            ("INCONCLUSIVE", "Inconclusive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "result_summary",
                    models.TextField(blank=True, help_text="Summary of test results"),
                ),
                (
                    "clinical_significance",
                    models.TextField(
                        blank=True, help_text="Clinical interpretation and significance"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, help_text="Follow-up recommendations"),
                ),
                (
                    "limitations",
                    models.TextField(
                        blank=True, help_text="Test limitations and disclaimers"
                    ),
                ),
                ("performed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("report_generated", models.BooleanField(default=False)),
                ("report_generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "report_file",
                    models.FileField(
                        blank=True, null=True, upload_to="molecular_reports/%Y/%m/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="molecular_diagnostics.molecularsample",
                    ),
                ),
            ],
            options={
                "verbose_name": "Molecular Result",
                "verbose_name_plural": "Molecular Results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MolecularTestPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("PCR", "PCR"),
                            ("RT_PCR", "Real-time PCR"),
                            ("NGS", "Next-Generation Sequencing"),
                            ("SANGER", "Sanger Sequencing"),
                            ("FISH", "Fluorescence In Situ Hybridization"),
                            ("MICROARRAY", "Microarray"),
                            ("MLPA", "MLPA"),
                            ("FRAGMENT", "Fragment Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "methodology",
                    models.TextField(
                        blank=True, help_text="Detailed methodology description"
                    ),
                ),
                (
                    "sample_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Required sample types, volume, and conditions",
                    ),
                ),
                (
                    "tat_hours",
                    models.PositiveIntegerField(
                        help_text="Target turnaround time in hours (SLA)"
                    ),
                ),
                (
                    "min_concentration_ng_ul",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum DNA/RNA concentration required",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "min_volume_ul",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum sample volume required",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "requires_extraction",
                    models.BooleanField(
                        default=True,
                        help_text="Does this test require DNA/RNA extraction?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gene_targets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="test_panels",
                        to="molecular_diagnostics.genetarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "Molecular Test Panel",
                "verbose_name_plural": "Molecular Test Panels",
                "ordering": ["name"],
            },
        ),
    ]
