# Generated by Django 6.0.2 on 2026-02-15 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("molecular_diagnostics", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="molecularsample",
            name="aliquot_of",
        ),
        migrations.AddField(
            model_name="molecularsample",
            name="derivation_type",
            field=models.CharField(
                choices=[
                    ("ORIGINAL", "Original Sample"),
                    ("ALIQUOT", "Aliquot"),
                    ("EXTRACT", "Extracted Material"),
                    ("LIBRARY", "Sequencing Library"),
                    ("DISSECTION", "Dissected Tissue"),
                    ("AMPLICON", "Amplified Product"),
                ],
                default="ORIGINAL",
                help_text="How this sample was derived from parent",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="molecularsample",
            name="parent_sample",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent sample this was derived from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_samples",
                to="molecular_diagnostics.molecularsample",
            ),
        ),
        migrations.CreateModel(
            name="ReflexRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the reflex rule", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of when and why this rule applies",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text='\n        JSON object defining trigger conditions. Examples:\n        {"interpretation": "POSITIVE"}\n        {"target": "GENE1", "result": "DETECTED"}\n        {"ct_value": {"lt": 30}}\n        {"and": [{"interpretation": "POSITIVE"}, {"ct_value": {"lt": 35}}]}\n        ',
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Rules with lower numbers are evaluated first",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this rule is currently active"
                    ),
                ),
                (
                    "auto_approve",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically approve the reflex test without review",
                    ),
                ),
                (
                    "require_confirmation",
                    models.BooleanField(
                        default=True,
                        help_text="Require user confirmation before ordering reflex test",
                    ),
                ),
                (
                    "notify_ordering_physician",
                    models.BooleanField(
                        default=True,
                        help_text="Send notification to ordering physician when reflex triggers",
                    ),
                ),
                (
                    "max_reflexes_per_sample",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Maximum number of times this rule can trigger per sample",
                    ),
                ),
                (
                    "clinical_rationale",
                    models.TextField(
                        blank=True,
                        help_text="Clinical justification for this reflex rule",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reflex_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reflex_test",
                    models.ForeignKey(
                        help_text="The test to automatically order when triggered",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflex_from_rules",
                        to="molecular_diagnostics.moleculartestpanel",
                    ),
                ),
                (
                    "trigger_test",
                    models.ForeignKey(
                        help_text="The test that triggers this reflex rule",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trigger_rules",
                        to="molecular_diagnostics.moleculartestpanel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reflex Rule",
                "verbose_name_plural": "Reflex Rules",
                "ordering": ["priority", "name"],
                "unique_together": {("trigger_test", "reflex_test", "conditions")},
            },
        ),
        migrations.CreateModel(
            name="ReflexTestOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Confirmation"),
                            ("CONFIRMED", "Confirmed"),
                            ("ORDERED", "Ordered"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_reflex_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_reflex_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reflex_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ordered_as_reflex",
                        to="molecular_diagnostics.molecularresult",
                    ),
                ),
                (
                    "reflex_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triggered_orders",
                        to="molecular_diagnostics.reflexrule",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflex_orders",
                        to="molecular_diagnostics.molecularsample",
                    ),
                ),
                (
                    "triggering_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggered_reflex_orders",
                        to="molecular_diagnostics.molecularresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reflex Test Order",
                "verbose_name_plural": "Reflex Test Orders",
                "ordering": ["-triggered_at"],
            },
        ),
    ]
