# Generated by Django 6.0.2 on 2026-02-16 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("molecular_diagnostics", "0003_remove_molecularsample_aliquot_of_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant_key",
                    models.CharField(
                        db_index=True,
                        help_text="Normalized variant identifier (chr-pos-ref-alt or rsID)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "hgvs_notation",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="HGVS notation for variant lookup",
                        max_length=300,
                    ),
                ),
                (
                    "dbsnp_id",
                    models.CharField(
                        blank=True, db_index=True, help_text="dbSNP rsID", max_length=50
                    ),
                ),
                (
                    "clinvar_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached ClinVar annotation data",
                    ),
                ),
                (
                    "clinvar_fetched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When ClinVar data was last fetched",
                        null=True,
                    ),
                ),
                (
                    "gnomad_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached gnomAD annotation data",
                    ),
                ),
                (
                    "gnomad_fetched_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When gnomAD data was last fetched",
                        null=True,
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this cache entry was used"
                    ),
                ),
                (
                    "last_hit_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this cache entry was accessed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Annotation Cache",
                "verbose_name_plural": "Annotation Cache Entries",
                "ordering": ["-hit_count", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="VariantAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annotation_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                            ("NOT_FOUND", "Not Found"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if annotation failed"
                    ),
                ),
                (
                    "clinvar_variation_id",
                    models.CharField(
                        blank=True, help_text="ClinVar Variation ID", max_length=50
                    ),
                ),
                (
                    "clinvar_allele_id",
                    models.CharField(
                        blank=True, help_text="ClinVar Allele ID", max_length=50
                    ),
                ),
                (
                    "clinical_significance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PATHOGENIC", "Pathogenic"),
                            ("LIKELY_PATHOGENIC", "Likely pathogenic"),
                            ("UNCERTAIN_SIGNIFICANCE", "Uncertain significance"),
                            ("LIKELY_BENIGN", "Likely benign"),
                            ("BENIGN", "Benign"),
                            ("CONFLICTING", "Conflicting interpretations"),
                            ("NOT_PROVIDED", "Not provided"),
                            ("DRUG_RESPONSE", "Drug response"),
                            ("RISK_FACTOR", "Risk factor"),
                            ("ASSOCIATION", "Association"),
                            ("PROTECTIVE", "Protective"),
                        ],
                        help_text="ClinVar clinical significance",
                        max_length=50,
                    ),
                ),
                (
                    "clinical_significance_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw clinical significance from ClinVar",
                        max_length=500,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRACTICE_GUIDELINE", "practice guideline"),
                            ("EXPERT_PANEL", "reviewed by expert panel"),
                            (
                                "MULTIPLE_SUBMITTERS",
                                "criteria provided, multiple submitters, no conflicts",
                            ),
                            ("SINGLE_SUBMITTER", "criteria provided, single submitter"),
                            (
                                "CONFLICTING",
                                "criteria provided, conflicting interpretations",
                            ),
                            ("NO_ASSERTION", "no assertion criteria provided"),
                            ("NO_CLASSIFICATION", "no classification provided"),
                        ],
                        help_text="ClinVar review status",
                        max_length=100,
                    ),
                ),
                (
                    "review_status_stars",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="ClinVar review status star rating (0-4)",
                        null=True,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of associated conditions/diseases",
                    ),
                ),
                (
                    "submitters",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of ClinVar submitters and their assertions",
                    ),
                ),
                (
                    "submission_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of ClinVar submissions", null=True
                    ),
                ),
                (
                    "last_evaluated",
                    models.DateField(
                        blank=True,
                        help_text="Date of last ClinVar evaluation",
                        null=True,
                    ),
                ),
                ("clinvar_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "genome_af",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="gnomAD genome allele frequency (overall)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "exome_af",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="gnomAD exome allele frequency (overall)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "genome_ac",
                    models.PositiveIntegerField(
                        blank=True, help_text="gnomAD genome allele count", null=True
                    ),
                ),
                (
                    "genome_an",
                    models.PositiveIntegerField(
                        blank=True, help_text="gnomAD genome allele number", null=True
                    ),
                ),
                (
                    "exome_ac",
                    models.PositiveIntegerField(
                        blank=True, help_text="gnomAD exome allele count", null=True
                    ),
                ),
                (
                    "exome_an",
                    models.PositiveIntegerField(
                        blank=True, help_text="gnomAD exome allele number", null=True
                    ),
                ),
                (
                    "genome_homozygotes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of homozygotes in gnomAD genomes",
                        null=True,
                    ),
                ),
                (
                    "exome_homozygotes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of homozygotes in gnomAD exomes",
                        null=True,
                    ),
                ),
                (
                    "populations",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Population-specific allele frequencies",
                    ),
                ),
                (
                    "max_population_af",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Maximum allele frequency across populations",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "max_population",
                    models.CharField(
                        blank=True,
                        help_text="Population with maximum allele frequency",
                        max_length=50,
                    ),
                ),
                (
                    "flags",
                    models.JSONField(
                        blank=True, default=list, help_text="gnomAD quality flags"
                    ),
                ),
                (
                    "gene_constraint",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Gene constraint metrics (pLI, LOEUF, etc.)",
                    ),
                ),
                ("gnomad_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "in_silico_predictions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="In-silico prediction scores (SIFT, PolyPhen, CADD, etc.)",
                    ),
                ),
                (
                    "pubmed_ids",
                    models.JSONField(
                        blank=True, default=list, help_text="Associated PubMed IDs"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annotated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annotations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cache_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="annotations",
                        to="molecular_diagnostics.annotationcache",
                    ),
                ),
                (
                    "variant_call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation",
                        to="molecular_diagnostics.variantcall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variant Annotation",
                "verbose_name_plural": "Variant Annotations",
                "ordering": ["-updated_at"],
            },
        ),
    ]
