# Generated by Django 6.0.2 on 2026-03-14 22:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "measurement_type",
                    models.CharField(
                        choices=[
                            ("TEMPERATURE", "Temperature"),
                            ("HUMIDITY", "Humidity"),
                            ("CO2", "CO2 Level"),
                            ("O2", "Oxygen Level"),
                            ("PRESSURE", "Pressure"),
                            ("DOOR", "Door Status"),
                            ("POWER", "Power Status"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (°C, %, etc.)", max_length=20
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Sensor Type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("mac_address", models.CharField(blank=True, max_length=17)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("location_description", models.CharField(blank=True, max_length=200)),
                ("reading_interval_minutes", models.PositiveIntegerField(default=15)),
                ("alert_enabled", models.BooleanField(default=True)),
                (
                    "warning_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "warning_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critical_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critical_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ACTIVE", "Active"),
                            ("MAINTENANCE", "Maintenance"),
                            ("RETIRED", "Retired"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("last_reading", models.DateTimeField(blank=True, null=True)),
                (
                    "last_reading_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("installed_date", models.DateField(blank=True, null=True)),
                ("calibration_date", models.DateField(blank=True, null=True)),
                ("next_calibration_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "storage_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitoring_devices",
                        to="storage.storageunit",
                    ),
                ),
                (
                    "sensor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sensors.sensortype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitoring Device",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                            ("ERROR", "Error"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="sensors.monitoringdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor Reading",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SensorAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("WARNING", "Warning"), ("CRITICAL", "Critical")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_sensor_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="sensors.monitoringdevice",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_sensor_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reading",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sensors.sensorreading",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sensor Alert",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertNotificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "severity_levels",
                    models.JSONField(
                        default=list, help_text="List of severities to notify on"
                    ),
                ),
                (
                    "notify_emails",
                    models.JSONField(
                        default=list, help_text="Additional email addresses"
                    ),
                ),
                (
                    "notify_sms",
                    models.JSONField(default=list, help_text="SMS phone numbers"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notify_users",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "devices",
                    models.ManyToManyField(blank=True, to="sensors.monitoringdevice"),
                ),
                (
                    "sensor_types",
                    models.ManyToManyField(blank=True, to="sensors.sensortype"),
                ),
            ],
            options={
                "verbose_name": "Alert Notification Rule",
            },
        ),
        migrations.AddIndex(
            model_name="sensorreading",
            index=models.Index(
                fields=["device", "timestamp"], name="sensors_sen_device__a87cca_idx"
            ),
        ),
    ]
