# Generated by Django 6.0.2 on 2026-02-15 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Friendly name for this connection", max_length=100
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("ASTM", "ASTM E1381/E1394"),
                            ("HL7", "HL7 v2.x"),
                            ("CUSTOM", "Custom Protocol"),
                        ],
                        default="ASTM",
                        max_length=10,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("TCP_SERVER", "TCP Server (Listen)"),
                            ("TCP_CLIENT", "TCP Client (Connect)"),
                            ("SERIAL", "Serial Port"),
                        ],
                        default="TCP_SERVER",
                        max_length=20,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        default="0.0.0.0",
                        help_text="IP address or hostname",
                        max_length=255,
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=5000, help_text="TCP port number"
                    ),
                ),
                (
                    "serial_port",
                    models.CharField(
                        blank=True,
                        help_text="Serial port (e.g., COM1, /dev/ttyUSB0)",
                        max_length=50,
                    ),
                ),
                (
                    "baud_rate",
                    models.PositiveIntegerField(
                        default=9600, help_text="Baud rate for serial connections"
                    ),
                ),
                (
                    "timeout",
                    models.PositiveIntegerField(
                        default=30, help_text="Connection timeout in seconds"
                    ),
                ),
                (
                    "retry_interval",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Retry interval in seconds after connection failure",
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum connection retry attempts"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this connection"
                    ),
                ),
                (
                    "auto_start",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically start connection on service startup",
                    ),
                ),
                (
                    "last_connection",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last successful connection time",
                        null=True,
                    ),
                ),
                (
                    "last_message",
                    models.DateTimeField(
                        blank=True, help_text="Last message received/sent", null=True
                    ),
                ),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Connected"),
                            ("DISCONNECTED", "Disconnected"),
                            ("CONNECTING", "Connecting"),
                            ("ERROR", "Error"),
                        ],
                        default="DISCONNECTED",
                        max_length=20,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, help_text="Last error message"),
                ),
                (
                    "protocol_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Protocol-specific configuration options",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instrument_connections_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="equipment.instrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instrument Connection",
                "verbose_name_plural": "Instrument Connections",
                "ordering": ["instrument__name", "name"],
                "unique_together": {("host", "port")},
            },
        ),
        migrations.CreateModel(
            name="WorklistExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "samples",
                    models.JSONField(
                        default=list,
                        help_text="List of sample IDs included in worklist",
                    ),
                ),
                (
                    "export_data",
                    models.JSONField(default=dict, help_text="Full worklist data"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("PARTIAL", "Partially Processed"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worklist_exports",
                        to="instruments.instrumentconnection",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="worklist_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Worklist Export",
                "verbose_name_plural": "Worklist Exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("INBOUND", "Inbound (from instrument)"),
                            ("OUTBOUND", "Outbound (to instrument)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("ASTM_HEADER", "ASTM Header"),
                            ("ASTM_PATIENT", "ASTM Patient"),
                            ("ASTM_ORDER", "ASTM Order"),
                            ("ASTM_RESULT", "ASTM Result"),
                            ("ASTM_COMMENT", "ASTM Comment"),
                            ("ASTM_TERMINATOR", "ASTM Terminator"),
                            ("ASTM_QUERY", "ASTM Query"),
                            ("HL7_ORM", "HL7 Order Message (ORM)"),
                            ("HL7_ORU", "HL7 Observation Result (ORU)"),
                            ("HL7_QRY", "HL7 Query Message (QRY)"),
                            ("HL7_ACK", "HL7 Acknowledgment (ACK)"),
                            ("HL7_ADT", "HL7 Admit/Discharge/Transfer (ADT)"),
                            ("RAW", "Raw Data"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "raw_message",
                    models.TextField(help_text="Raw message as received/sent"),
                ),
                (
                    "parsed_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Parsed message data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PARSED", "Parsed"),
                            ("PROCESSED", "Processed"),
                            ("SENT", "Sent"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("ERROR", "Error"),
                            ("IGNORED", "Ignored"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if processing failed"
                    ),
                ),
                (
                    "related_sample_id",
                    models.CharField(
                        blank=True, help_text="Sample ID from message", max_length=100
                    ),
                ),
                (
                    "related_patient_id",
                    models.CharField(
                        blank=True, help_text="Patient ID from message", max_length=100
                    ),
                ),
                (
                    "related_order_id",
                    models.CharField(
                        blank=True, help_text="Order ID from message", max_length=100
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checksum",
                    models.CharField(
                        blank=True, help_text="Message checksum", max_length=10
                    ),
                ),
                (
                    "checksum_valid",
                    models.BooleanField(
                        blank=True, help_text="Was the checksum valid?", null=True
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_logs",
                        to="instruments.instrumentconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Log",
                "verbose_name_plural": "Message Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["connection", "timestamp"],
                        name="instruments_connect_8610e7_idx",
                    ),
                    models.Index(
                        fields=["direction", "status"],
                        name="instruments_directi_e010e3_idx",
                    ),
                    models.Index(
                        fields=["related_sample_id"],
                        name="instruments_related_d2678f_idx",
                    ),
                    models.Index(
                        fields=["message_type"], name="instruments_message_6b5f60_idx"
                    ),
                ],
            },
        ),
    ]
