# Generated by Django 6.0.2 on 2026-02-16 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("molecular_diagnostics", "0004_annotationcache_variantannotation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Generic drug name", max_length=200),
                ),
                (
                    "brand_names",
                    models.JSONField(
                        blank=True, default=list, help_text="List of brand names"
                    ),
                ),
                (
                    "drug_class",
                    models.CharField(
                        choices=[
                            ("ANALGESIC", "Analgesic"),
                            ("ANTIDEPRESSANT", "Antidepressant"),
                            ("ANTICOAGULANT", "Anticoagulant"),
                            ("ANTIPSYCHOTIC", "Antipsychotic"),
                            ("CARDIOVASCULAR", "Cardiovascular"),
                            ("ONCOLOGY", "Oncology"),
                            ("IMMUNOSUPPRESSANT", "Immunosuppressant"),
                            ("ANTIPLATELET", "Antiplatelet"),
                            ("PPI", "Proton Pump Inhibitor"),
                            ("ANTIBIOTIC", "Antibiotic"),
                            ("ANTIVIRAL", "Antiviral"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                (
                    "rxnorm_id",
                    models.CharField(
                        blank=True, help_text="RxNorm Concept ID", max_length=50
                    ),
                ),
                (
                    "drugbank_id",
                    models.CharField(
                        blank=True, help_text="DrugBank ID", max_length=50
                    ),
                ),
                (
                    "atc_code",
                    models.CharField(blank=True, help_text="ATC Code", max_length=20),
                ),
                ("description", models.TextField(blank=True)),
                ("mechanism_of_action", models.TextField(blank=True)),
                (
                    "has_cpic_guideline",
                    models.BooleanField(
                        default=False, help_text="Has CPIC dosing guideline"
                    ),
                ),
                (
                    "has_fda_label",
                    models.BooleanField(
                        default=False, help_text="Has PGx information in FDA label"
                    ),
                ),
                (
                    "cpic_level",
                    models.CharField(
                        blank=True,
                        help_text="CPIC evidence level (A, B, C, D)",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Drug",
                "verbose_name_plural": "Drugs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PGxGene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Gene symbol (e.g., CYP2D6)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Full gene name", max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CYP", "Cytochrome P450"),
                            ("TRANSPORTER", "Drug Transporter"),
                            ("PHASE2", "Phase II Enzyme"),
                            ("TARGET", "Drug Target"),
                            ("HLA", "HLA Gene"),
                            ("OTHER", "Other"),
                        ],
                        default="CYP",
                        max_length=20,
                    ),
                ),
                (
                    "ensembl_id",
                    models.CharField(
                        blank=True, help_text="Ensembl Gene ID", max_length=50
                    ),
                ),
                (
                    "ncbi_gene_id",
                    models.CharField(
                        blank=True, help_text="NCBI Gene ID", max_length=50
                    ),
                ),
                (
                    "pharmvar_id",
                    models.CharField(
                        blank=True, help_text="PharmVar Gene ID", max_length=50
                    ),
                ),
                ("chromosome", models.CharField(blank=True, max_length=10)),
                ("start_position", models.BigIntegerField(blank=True, null=True)),
                ("end_position", models.BigIntegerField(blank=True, null=True)),
                (
                    "reference_sequence",
                    models.CharField(
                        blank=True,
                        help_text="Reference sequence (e.g., NG_008376.4)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Gene function and PGx relevance"
                    ),
                ),
                (
                    "clinical_importance",
                    models.TextField(
                        blank=True, help_text="Clinical significance notes"
                    ),
                ),
                (
                    "uses_activity_score",
                    models.BooleanField(
                        default=True,
                        help_text="Whether phenotype is determined by activity score",
                    ),
                ),
                (
                    "copy_number_relevant",
                    models.BooleanField(
                        default=False,
                        help_text="Whether gene duplications affect phenotype (e.g., CYP2D6)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gene_target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pgx_genes",
                        to="molecular_diagnostics.genetarget",
                    ),
                ),
            ],
            options={
                "verbose_name": "PGx Gene",
                "verbose_name_plural": "PGx Genes",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="DrugGeneInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("PK", "Pharmacokinetic"),
                            ("PD", "Pharmacodynamic"),
                            ("ADR", "Adverse Drug Reaction"),
                            ("EFFICACY", "Efficacy"),
                            ("DOSING", "Dosing"),
                        ],
                        default="PK",
                        max_length=20,
                    ),
                ),
                (
                    "evidence_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1A", "1A - Strong"),
                            ("1B", "1B - Moderate"),
                            ("2A", "2A - Weak"),
                            ("2B", "2B - Very Weak"),
                            ("3", "3 - Annotation"),
                            ("4", "4 - Insufficient"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cpic_guideline_url", models.URLField(blank=True)),
                (
                    "cpic_publication_pmid",
                    models.CharField(
                        blank=True,
                        help_text="PMID for CPIC guideline publication",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the drug-gene interaction"
                    ),
                ),
                (
                    "clinical_summary",
                    models.TextField(
                        blank=True, help_text="Clinical summary of interaction"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gene_interactions",
                        to="pharmacogenomics.drug",
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drug_interactions",
                        to="pharmacogenomics.pgxgene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drug-Gene Interaction",
                "verbose_name_plural": "Drug-Gene Interactions",
                "ordering": ["drug", "gene"],
                "unique_together": {("drug", "gene")},
            },
        ),
        migrations.CreateModel(
            name="PGxPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "target_regions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Target regions covered by panel",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "genes",
                    models.ManyToManyField(
                        related_name="panels", to="pharmacogenomics.pgxgene"
                    ),
                ),
                (
                    "molecular_panel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pgx_panels",
                        to="molecular_diagnostics.moleculartestpanel",
                    ),
                ),
            ],
            options={
                "verbose_name": "PGx Panel",
                "verbose_name_plural": "PGx Panels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Phenotype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("PM", "Poor Metabolizer"),
                            ("IM", "Intermediate Metabolizer"),
                            ("NM", "Normal Metabolizer"),
                            ("RM", "Rapid Metabolizer"),
                            ("UM", "Ultrarapid Metabolizer"),
                            ("INDETERMINATE", "Indeterminate"),
                            ("POSSIBLE_IM", "Possible Intermediate Metabolizer"),
                            ("LIKELY_PM", "Likely Poor Metabolizer"),
                            ("LIKELY_IM", "Likely Intermediate Metabolizer"),
                        ],
                        help_text="Phenotype code",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(help_text="Display name", max_length=100)),
                (
                    "activity_score_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum activity score for this phenotype",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "activity_score_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum activity score for this phenotype",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "example_diplotypes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Example diplotypes for this phenotype",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "clinical_implications",
                    models.TextField(
                        blank=True, help_text="Clinical implications of this phenotype"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phenotypes",
                        to="pharmacogenomics.pgxgene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phenotype",
                "verbose_name_plural": "Phenotypes",
                "ordering": ["gene", "sort_order", "code"],
                "unique_together": {("gene", "code")},
            },
        ),
        migrations.CreateModel(
            name="DrugRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_strength",
                    models.CharField(
                        choices=[
                            ("STRONG", "Strong"),
                            ("MODERATE", "Moderate"),
                            ("OPTIONAL", "Optional"),
                        ],
                        default="STRONG",
                        max_length=20,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Use standard dose"),
                            ("REDUCE", "Reduce dose"),
                            ("INCREASE", "Increase dose"),
                            ("AVOID", "Avoid drug"),
                            ("ALTERNATIVE", "Use alternative drug"),
                            ("MONITOR", "Enhanced monitoring"),
                            ("CAUTION", "Use with caution"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "recommendation_text",
                    models.TextField(help_text="Full recommendation text"),
                ),
                (
                    "dosing_guidance",
                    models.TextField(blank=True, help_text="Specific dosing guidance"),
                ),
                (
                    "alternative_drugs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of alternative drug options",
                    ),
                ),
                (
                    "clinical_context",
                    models.TextField(
                        blank=True, help_text="Clinical context and considerations"
                    ),
                ),
                (
                    "monitoring_recommendations",
                    models.TextField(
                        blank=True, help_text="Monitoring recommendations"
                    ),
                ),
                (
                    "reference_pmids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="PubMed IDs for supporting references",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="pharmacogenomics.druggeneinteraction",
                    ),
                ),
                (
                    "phenotype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="pharmacogenomics.phenotype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drug Recommendation",
                "verbose_name_plural": "Drug Recommendations",
                "ordering": ["interaction__drug__name", "phenotype__gene__symbol"],
                "unique_together": {("interaction", "phenotype")},
            },
        ),
        migrations.CreateModel(
            name="StarAllele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Star allele name (e.g., *1, *2, *17)", max_length=50
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal Function"),
                            ("INCREASED", "Increased Function"),
                            ("DECREASED", "Decreased Function"),
                            ("NO_FUNCTION", "No Function"),
                            ("UNCERTAIN", "Uncertain Function"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "activity_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Activity score (e.g., 0, 0.5, 1, 2)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "defining_variants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of defining variants for this allele",
                    ),
                ),
                (
                    "pharmvar_id",
                    models.CharField(
                        blank=True, help_text="PharmVar Allele ID", max_length=100
                    ),
                ),
                (
                    "cpic_allele_id",
                    models.CharField(
                        blank=True, help_text="CPIC Allele ID", max_length=100
                    ),
                ),
                (
                    "population_frequencies",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Allele frequencies by population",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("clinical_significance", models.TextField(blank=True)),
                (
                    "is_reference",
                    models.BooleanField(
                        default=False, help_text="Is this the reference allele (*1)?"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alleles",
                        to="pharmacogenomics.pgxgene",
                    ),
                ),
            ],
            options={
                "verbose_name": "Star Allele",
                "verbose_name_plural": "Star Alleles",
                "ordering": ["gene", "name"],
                "unique_together": {("gene", "name")},
            },
        ),
        migrations.CreateModel(
            name="PGxResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CALLING", "Diplotype Calling"),
                            ("CALLED", "Called"),
                            ("REVIEWED", "Reviewed"),
                            ("REPORTED", "Reported"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "diplotype",
                    models.CharField(
                        blank=True,
                        help_text="Diplotype string (e.g., *1/*17)",
                        max_length=100,
                    ),
                ),
                (
                    "copy_number",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Gene copy number", null=True
                    ),
                ),
                (
                    "has_hybrid",
                    models.BooleanField(default=False, help_text="Has hybrid allele"),
                ),
                (
                    "activity_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated activity score",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "detected_variants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Variants detected for this gene",
                    ),
                ),
                (
                    "calling_method",
                    models.CharField(
                        blank=True,
                        help_text="Method used for diplotype calling",
                        max_length=50,
                    ),
                ),
                (
                    "calling_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Confidence score (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "clinical_summary",
                    models.TextField(
                        blank=True, help_text="Clinical summary for this gene result"
                    ),
                ),
                (
                    "interpretation",
                    models.TextField(blank=True, help_text="Detailed interpretation"),
                ),
                ("called_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "called_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pgx_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="pharmacogenomics.pgxgene",
                    ),
                ),
                (
                    "molecular_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pgx_results",
                        to="molecular_diagnostics.molecularresult",
                    ),
                ),
                (
                    "panel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="pharmacogenomics.pgxpanel",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pgx_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phenotype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="pharmacogenomics.phenotype",
                    ),
                ),
                (
                    "allele1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results_as_allele1",
                        to="pharmacogenomics.starallele",
                    ),
                ),
                (
                    "allele2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results_as_allele2",
                        to="pharmacogenomics.starallele",
                    ),
                ),
            ],
            options={
                "verbose_name": "PGx Result",
                "verbose_name_plural": "PGx Results",
                "ordering": ["-created_at"],
                "unique_together": {("molecular_result", "gene")},
            },
        ),
        migrations.CreateModel(
            name="PGxDrugResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_text",
                    models.TextField(
                        blank=True, help_text="Personalized recommendation text"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STANDARD", "Use standard dose"),
                            ("REDUCE", "Reduce dose"),
                            ("INCREASE", "Increase dose"),
                            ("AVOID", "Avoid drug"),
                            ("ALTERNATIVE", "Use alternative drug"),
                            ("MONITOR", "Enhanced monitoring"),
                            ("CAUTION", "Use with caution"),
                        ],
                        max_length=20,
                    ),
                ),
                ("clinical_notes", models.TextField(blank=True)),
                (
                    "is_actionable",
                    models.BooleanField(
                        default=True, help_text="Requires clinical action"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_results",
                        to="pharmacogenomics.drug",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patient_results",
                        to="pharmacogenomics.drugrecommendation",
                    ),
                ),
                (
                    "pgx_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drug_results",
                        to="pharmacogenomics.pgxresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "PGx Drug Result",
                "verbose_name_plural": "PGx Drug Results",
                "ordering": ["pgx_result", "drug__name"],
                "unique_together": {("pgx_result", "drug")},
            },
        ),
    ]
