# Generated by Django 6.0.2 on 2026-02-15 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab_management", "0021_remove_patient_barcode_image_url_and_more"),
        ("tenants", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakpointType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Breakpoint Type",
                "verbose_name_plural": "Breakpoint Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Family",
                "verbose_name_plural": "Families",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Host",
                "verbose_name_plural": "Hosts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Kingdom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Kingdom",
                "verbose_name_plural": "Kingdoms",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["organism_class", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrganismClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
                "ordering": ["phylum", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteOfInfection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Site of Infection",
                "verbose_name_plural": "Sites of Infection",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TestMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Test Method",
                "verbose_name_plural": "Test Methods",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AntibioticClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent_class",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent antibiotic class for hierarchical classification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subclasses",
                        to="microbiology.antibioticclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antibiotic Class",
                "verbose_name_plural": "Antibiotic Classes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Antibiotic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "antibiotic_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique antibiotic identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "abbreviation",
                    models.CharField(
                        help_text="Standard 2-3 letter abbreviation", max_length=10
                    ),
                ),
                (
                    "whonet_abx_code",
                    models.CharField(
                        blank=True, help_text="WHONET antibiotic code", max_length=10
                    ),
                ),
                (
                    "eucast_code",
                    models.CharField(
                        blank=True, help_text="EUCAST code", max_length=20
                    ),
                ),
                (
                    "clsi_code",
                    models.CharField(blank=True, help_text="CLSI code", max_length=20),
                ),
                (
                    "atc_code",
                    models.CharField(
                        blank=True, help_text="ATC classification code", max_length=10
                    ),
                ),
                (
                    "loinc_disk",
                    models.CharField(
                        blank=True,
                        help_text="LOINC code for disk diffusion",
                        max_length=20,
                    ),
                ),
                (
                    "loinc_mic",
                    models.CharField(
                        blank=True, help_text="LOINC code for MIC", max_length=20
                    ),
                ),
                (
                    "loinc_etest",
                    models.CharField(
                        blank=True, help_text="LOINC code for E-test", max_length=20
                    ),
                ),
                (
                    "potency",
                    models.CharField(
                        blank=True, help_text="e.g., 10 ug, 30 ug", max_length=50
                    ),
                ),
                (
                    "disk_content_ug",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Disk content in micrograms",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("human_use", models.BooleanField(default=True)),
                ("veterinary_use", models.BooleanField(default=False)),
                (
                    "screening_drug",
                    models.BooleanField(
                        default=False, help_text="Used for resistance screening"
                    ),
                ),
                (
                    "confirmatory_drug",
                    models.BooleanField(
                        default=False, help_text="Used for resistance confirmation"
                    ),
                ),
                ("spectrum_gram_positive", models.BooleanField(default=True)),
                ("spectrum_gram_negative", models.BooleanField(default=True)),
                ("spectrum_anaerobes", models.BooleanField(default=False)),
                ("spectrum_fungi", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "antibiotic_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="antibiotics",
                        to="microbiology.antibioticclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antibiotic",
                "verbose_name_plural": "Antibiotics",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ASTGuideline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("CLSI", "CLSI"),
                            ("EUCAST", "EUCAST"),
                            ("SFM", "SFM (French)"),
                            ("DIN", "DIN (German)"),
                            ("BSAC", "BSAC (British)"),
                            ("SRGA", "SRGA (Swedish)"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="e.g., M100-Ed34", max_length=20
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "AST Guideline",
                "verbose_name_plural": "AST Guidelines",
                "ordering": ["-year", "name"],
                "unique_together": {("name", "year")},
            },
        ),
        migrations.CreateModel(
            name="ASTMPanelAntibiotic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(default=0, help_text="Display order"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, help_text="Must be tested"),
                ),
                (
                    "is_reported",
                    models.BooleanField(default=True, help_text="Include in report"),
                ),
                (
                    "is_screening",
                    models.BooleanField(
                        default=False, help_text="Screening antibiotic"
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=200)),
                (
                    "antibiotic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="microbiology.antibiotic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Panel Antibiotic",
                "verbose_name_plural": "Panel Antibiotics",
                "ordering": ["panel", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="ASTPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "panel_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique panel identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                (
                    "panel_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard Panel"),
                            ("SCREENING", "Screening Panel"),
                            ("EXTENDED", "Extended Panel"),
                            ("TARGETED", "Targeted Panel"),
                            ("STAT", "STAT/Emergency Panel"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "organism_groups",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of organism group names this panel applies to",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "antibiotics",
                    models.ManyToManyField(
                        related_name="ast_panels",
                        through="microbiology.ASTMPanelAntibiotic",
                        to="microbiology.antibiotic",
                    ),
                ),
                (
                    "guideline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="panels",
                        to="microbiology.astguideline",
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ast_panels",
                        to="tenants.laboratory",
                    ),
                ),
            ],
            options={
                "verbose_name": "AST Panel",
                "verbose_name_plural": "AST Panels",
                "ordering": ["laboratory", "name"],
            },
        ),
        migrations.AddField(
            model_name="astmpanelantibiotic",
            name="panel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="panel_antibiotics",
                to="microbiology.astpanel",
            ),
        ),
        migrations.CreateModel(
            name="Genus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genera",
                        to="microbiology.family",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genus",
                "verbose_name_plural": "Genera",
                "ordering": ["family", "name"],
                "unique_together": {("family", "name")},
            },
        ),
        migrations.CreateModel(
            name="MicrobiologySample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique sample identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "specimen_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood"),
                            ("URINE", "Urine"),
                            ("SPUTUM", "Sputum"),
                            ("STOOL", "Stool"),
                            ("CSF", "Cerebrospinal Fluid"),
                            ("WOUND", "Wound Swab"),
                            ("TISSUE", "Tissue"),
                            ("THROAT", "Throat Swab"),
                            ("NASAL", "Nasal Swab"),
                            ("RESPIRATORY", "Respiratory"),
                            ("GENITAL", "Genital"),
                            ("FLUID", "Body Fluid"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "specimen_source",
                    models.CharField(
                        blank=True, help_text="Specific source/site", max_length=100
                    ),
                ),
                ("collection_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "received_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("IN_PROCESS", "In Process"),
                            ("CULTURE_SETUP", "Culture Setup"),
                            ("INCUBATION", "Incubation"),
                            ("IDENTIFICATION", "Identification"),
                            ("AST_PENDING", "AST Pending"),
                            ("AST_COMPLETE", "AST Complete"),
                            ("REVIEW", "Review"),
                            ("REPORTED", "Reported"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "culture_type",
                    models.CharField(
                        blank=True, help_text="e.g., Aerobic, Anaerobic", max_length=50
                    ),
                ),
                ("culture_setup_datetime", models.DateTimeField(blank=True, null=True)),
                ("incubation_start", models.DateTimeField(blank=True, null=True)),
                (
                    "incubation_temperature",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("clinical_info", models.TextField(blank=True)),
                (
                    "antibiotics_prior",
                    models.TextField(blank=True, help_text="Prior antibiotic therapy"),
                ),
                ("growth_observed", models.BooleanField(blank=True, null=True)),
                ("preliminary_result", models.TextField(blank=True)),
                ("final_result", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_micro_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microbiology_samples",
                        to="lab_management.laborder",
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microbiology_samples",
                        to="tenants.laboratory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Microbiology Sample",
                "verbose_name_plural": "Microbiology Samples",
                "ordering": ["-received_datetime"],
            },
        ),
        migrations.AddField(
            model_name="family",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="families",
                to="microbiology.order",
            ),
        ),
        migrations.CreateModel(
            name="Organism",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organism_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique organism identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("species", models.CharField(max_length=100)),
                ("subspecies", models.CharField(blank=True, max_length=100)),
                ("common_name", models.CharField(blank=True, max_length=200)),
                (
                    "whonet_org_code",
                    models.CharField(
                        blank=True, help_text="WHONET organism code", max_length=20
                    ),
                ),
                (
                    "sct_code",
                    models.CharField(
                        blank=True, help_text="SNOMED-CT code", max_length=20
                    ),
                ),
                (
                    "ncbi_tax_id",
                    models.CharField(
                        blank=True, help_text="NCBI Taxonomy ID", max_length=20
                    ),
                ),
                (
                    "organism_type",
                    models.CharField(
                        choices=[
                            ("BACTERIA", "Bacteria"),
                            ("FUNGUS", "Fungus"),
                            ("PARASITE", "Parasite"),
                            ("VIRUS", "Virus"),
                            ("MYCOBACTERIA", "Mycobacteria"),
                            ("YEAST", "Yeast"),
                            ("MOLD", "Mold"),
                        ],
                        default="BACTERIA",
                        max_length=20,
                    ),
                ),
                (
                    "morphology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COCCI", "Cocci"),
                            ("BACILLI", "Bacilli"),
                            ("COCCOBACILLI", "Coccobacilli"),
                            ("SPIROCHETE", "Spirochete"),
                            ("PLEOMORPHIC", "Pleomorphic"),
                            ("FILAMENTOUS", "Filamentous"),
                            ("YEAST", "Yeast"),
                            ("DIMORPHIC", "Dimorphic"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gram_stain",
                    models.CharField(
                        choices=[
                            ("POSITIVE", "Gram Positive"),
                            ("NEGATIVE", "Gram Negative"),
                            ("VARIABLE", "Gram Variable"),
                            ("NA", "Not Applicable"),
                        ],
                        default="NA",
                        max_length=20,
                    ),
                ),
                (
                    "anaerobe",
                    models.BooleanField(default=False, help_text="Obligate anaerobe"),
                ),
                ("facultative_anaerobe", models.BooleanField(default=False)),
                ("is_pathogen", models.BooleanField(default=True)),
                ("is_opportunistic", models.BooleanField(default=False)),
                (
                    "biosafety_level",
                    models.PositiveSmallIntegerField(default=2, help_text="BSL 1-4"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisms",
                        to="microbiology.family",
                    ),
                ),
                (
                    "genus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisms",
                        to="microbiology.genus",
                    ),
                ),
                (
                    "kingdom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisms",
                        to="microbiology.kingdom",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisms",
                        to="microbiology.order",
                    ),
                ),
                (
                    "organism_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organisms",
                        to="microbiology.organismclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organism",
                "verbose_name_plural": "Organisms",
                "ordering": ["genus__name", "species"],
            },
        ),
        migrations.CreateModel(
            name="Breakpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organism_group",
                    models.CharField(
                        blank=True,
                        help_text="Organism group name (e.g., 'Enterobacteriaceae') when not specific",
                        max_length=200,
                    ),
                ),
                (
                    "susceptible_mic",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="MIC <= this value is Susceptible",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "intermediate_mic_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="MIC >= this value is Intermediate (low bound)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "intermediate_mic_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="MIC <= this value is Intermediate (high bound)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "resistant_mic",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="MIC >= this value is Resistant",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "susceptible_disk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Zone diameter >= this value is Susceptible",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "intermediate_disk_low",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Zone diameter >= this value is Intermediate (low bound)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "intermediate_disk_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Zone diameter <= this value is Intermediate (high bound)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "resistant_disk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Zone diameter <= this value is Resistant",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "ecoff_mic",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Epidemiological cut-off for MIC",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "ecoff_disk",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Epidemiological cut-off for disk",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "antibiotic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakpoints",
                        to="microbiology.antibiotic",
                    ),
                ),
                (
                    "guideline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakpoints",
                        to="microbiology.astguideline",
                    ),
                ),
                (
                    "breakpoint_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="breakpoints",
                        to="microbiology.breakpointtype",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="breakpoints",
                        to="microbiology.host",
                    ),
                ),
                (
                    "organism",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific organism, or null for organism group",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="breakpoints",
                        to="microbiology.organism",
                    ),
                ),
                (
                    "site_of_infection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="breakpoints",
                        to="microbiology.siteofinfection",
                    ),
                ),
                (
                    "test_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="breakpoints",
                        to="microbiology.testmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Breakpoint",
                "verbose_name_plural": "Breakpoints",
                "ordering": ["guideline", "antibiotic", "organism"],
            },
        ),
        migrations.AddField(
            model_name="astpanel",
            name="organisms",
            field=models.ManyToManyField(
                blank=True, related_name="ast_panels", to="microbiology.organism"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="organism_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="microbiology.organismclass",
            ),
        ),
        migrations.CreateModel(
            name="OrganismResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique result identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "identification_method",
                    models.CharField(
                        choices=[
                            ("MALDI-TOF", "MALDI-TOF MS"),
                            ("BIOCHEMICAL", "Biochemical Tests"),
                            ("VITEK", "VITEK"),
                            ("API", "API System"),
                            ("PCR", "PCR"),
                            ("SEQUENCING", "Sequencing"),
                            ("MORPHOLOGY", "Morphology"),
                            ("OTHER", "Other"),
                        ],
                        default="MALDI-TOF",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Identification confidence score",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "identification_datetime",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "quantity",
                    models.CharField(
                        choices=[
                            ("NONE", "No Growth"),
                            ("RARE", "Rare"),
                            ("FEW", "Few"),
                            ("MODERATE", "Moderate"),
                            ("MANY", "Many"),
                            ("HEAVY", "Heavy Growth"),
                            ("CFU_COUNT", "CFU Count"),
                        ],
                        default="MODERATE",
                        max_length=20,
                    ),
                ),
                (
                    "cfu_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Colony forming units per mL", null=True
                    ),
                ),
                ("colony_description", models.CharField(blank=True, max_length=200)),
                (
                    "is_significant",
                    models.BooleanField(
                        default=True, help_text="Clinically significant isolate"
                    ),
                ),
                ("is_contaminant", models.BooleanField(default=False)),
                ("requires_ast", models.BooleanField(default=True)),
                (
                    "sequence_number",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Isolate sequence number"
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ast_panel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organism_results",
                        to="microbiology.astpanel",
                    ),
                ),
                (
                    "identified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identified_organisms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organism",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="microbiology.organism",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organism_results",
                        to="microbiology.microbiologysample",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organism Result",
                "verbose_name_plural": "Organism Results",
                "ordering": ["sample", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="Phylum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                (
                    "kingdom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phyla",
                        to="microbiology.kingdom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phylum",
                "verbose_name_plural": "Phyla",
                "ordering": ["kingdom", "name"],
                "unique_together": {("kingdom", "name")},
            },
        ),
        migrations.AddField(
            model_name="organismclass",
            name="phylum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="microbiology.phylum",
            ),
        ),
        migrations.AddField(
            model_name="organism",
            name="phylum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organisms",
                to="microbiology.phylum",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="astmpanelantibiotic",
            unique_together={("panel", "antibiotic")},
        ),
        migrations.AlterUniqueTogether(
            name="family",
            unique_together={("order", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="astpanel",
            unique_together={("laboratory", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("organism_class", "name")},
        ),
        migrations.CreateModel(
            name="ASTResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_method",
                    models.CharField(
                        choices=[
                            ("MIC", "MIC"),
                            ("DISK", "Disk Diffusion"),
                            ("ETEST", "E-Test"),
                            ("GRADIENT", "Gradient Strip"),
                            ("AUTOMATED", "Automated System"),
                        ],
                        default="MIC",
                        max_length=20,
                    ),
                ),
                (
                    "raw_value",
                    models.CharField(
                        help_text="Raw MIC or zone diameter value", max_length=20
                    ),
                ),
                (
                    "mic_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="MIC in mg/L",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "zone_diameter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Zone diameter in mm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "interpretation",
                    models.CharField(
                        choices=[
                            ("S", "Susceptible"),
                            ("I", "Intermediate"),
                            ("R", "Resistant"),
                            ("SDD", "Susceptible-Dose Dependent"),
                            ("NS", "Non-Susceptible"),
                            ("NI", "No Interpretation"),
                        ],
                        max_length=5,
                    ),
                ),
                ("is_manual_override", models.BooleanField(default=False)),
                ("original_interpretation", models.CharField(blank=True, max_length=5)),
                ("override_reason", models.TextField(blank=True)),
                ("is_reported", models.BooleanField(default=True)),
                ("report_comment", models.CharField(blank=True, max_length=200)),
                ("tested_datetime", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "antibiotic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ast_results",
                        to="microbiology.antibiotic",
                    ),
                ),
                (
                    "interpretation_guideline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ast_results",
                        to="microbiology.astguideline",
                    ),
                ),
                (
                    "tested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tested_ast_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "breakpoint_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ast_results",
                        to="microbiology.breakpoint",
                    ),
                ),
                (
                    "organism_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ast_results",
                        to="microbiology.organismresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "AST Result",
                "verbose_name_plural": "AST Results",
                "ordering": ["organism_result", "antibiotic"],
                "unique_together": {("organism_result", "antibiotic", "test_method")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="organismclass",
            unique_together={("phylum", "name")},
        ),
    ]
