# Generated by Django 6.0.2 on 2026-02-15 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab_management", "0021_remove_patient_barcode_image_url_and_more"),
        ("molecular_diagnostics", "0003_remove_molecularsample_aliquot_of_and_more"),
        ("tenants", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InflammationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Inflammation Type",
                "verbose_name_plural": "Inflammation Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PathologyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "requires_gross",
                    models.BooleanField(
                        default=True, help_text="Requires gross examination"
                    ),
                ),
                (
                    "requires_microscopic",
                    models.BooleanField(
                        default=True, help_text="Requires microscopic examination"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Pathology Type",
                "verbose_name_plural": "Pathology Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpecimenType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("collection_method", models.CharField(blank=True, max_length=100)),
                ("container_type", models.CharField(blank=True, max_length=100)),
                (
                    "fixative",
                    models.CharField(
                        blank=True, help_text="Required fixative", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Specimen Type",
                "verbose_name_plural": "Specimen Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StainingProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "stain_type",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("SPECIAL", "Special Stain"),
                            ("IHC", "Immunohistochemistry"),
                            ("ISH", "In Situ Hybridization"),
                            ("FISH", "FISH"),
                            ("OTHER", "Other"),
                        ],
                        default="ROUTINE",
                        max_length=20,
                    ),
                ),
                (
                    "antibody",
                    models.CharField(
                        blank=True, help_text="For IHC stains", max_length=100
                    ),
                ),
                (
                    "clone",
                    models.CharField(
                        blank=True, help_text="Antibody clone", max_length=50
                    ),
                ),
                ("dilution", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Staining Protocol",
                "verbose_name_plural": "Staining Protocols",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TumorMorphology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ICD-O-3 morphology code", max_length=10, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "behavior",
                    models.CharField(
                        choices=[
                            ("0", "Benign"),
                            ("1", "Uncertain"),
                            ("2", "In situ"),
                            ("3", "Malignant, primary"),
                            ("6", "Malignant, metastatic"),
                            ("9", "Malignant, uncertain"),
                        ],
                        default="3",
                        max_length=1,
                    ),
                ),
                ("typical_grade", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tumor Morphology",
                "verbose_name_plural": "Tumor Morphologies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Histology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "histology_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique histology identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("clinical_history", models.TextField(blank=True)),
                (
                    "surgical_number",
                    models.CharField(
                        blank=True, help_text="Surgical pathology number", max_length=50
                    ),
                ),
                ("accession_number", models.CharField(blank=True, max_length=50)),
                (
                    "h_and_e_barcode",
                    models.CharField(
                        blank=True, help_text="H&E slide barcode", max_length=100
                    ),
                ),
                (
                    "fixation_type",
                    models.CharField(
                        choices=[
                            ("FORMALIN", "Formalin"),
                            ("ALCOHOL", "Alcohol"),
                            ("FROZEN", "Frozen"),
                            ("FRESH", "Fresh"),
                            ("OTHER", "Other"),
                        ],
                        default="FORMALIN",
                        max_length=20,
                    ),
                ),
                ("fixation_start", models.DateTimeField(blank=True, null=True)),
                ("fixation_end", models.DateTimeField(blank=True, null=True)),
                ("block_count", models.PositiveSmallIntegerField(default=1)),
                ("slide_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "tumor_cell_content",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tumor cell percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "necrosis_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Necrosis percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "tissue_adequacy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ADEQUATE", "Adequate"),
                            ("SUBOPTIMAL", "Suboptimal"),
                            ("INADEQUATE", "Inadequate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("GROSSING", "Grossing"),
                            ("PROCESSING", "Processing"),
                            ("EMBEDDING", "Embedding"),
                            ("CUTTING", "Cutting"),
                            ("STAINING", "Staining"),
                            ("COVERSLIPPING", "Coverslipping"),
                            ("QC", "Quality Control"),
                            ("READY", "Ready for Review"),
                            ("IN_REVIEW", "In Review"),
                            ("REPORTED", "Reported"),
                            ("ARCHIVED", "Archived"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "received_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("grossing_datetime", models.DateTimeField(blank=True, null=True)),
                ("processed_datetime", models.DateTimeField(blank=True, null=True)),
                ("gross_description", models.TextField(blank=True)),
                (
                    "gross_measurements",
                    models.CharField(
                        blank=True, help_text="e.g., 3.0 x 2.5 x 1.5 cm", max_length=200
                    ),
                ),
                (
                    "gross_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in grams",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("gross_photo_count", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("is_stat", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_histology",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histology_samples",
                        to="lab_management.laborder",
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histology_samples",
                        to="tenants.laboratory",
                    ),
                ),
                (
                    "molecular_sample",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="histology_samples",
                        to="molecular_diagnostics.molecularsample",
                    ),
                ),
                (
                    "specimen_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="histology_samples",
                        to="pathology.specimentype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histology",
                "verbose_name_plural": "Histologies",
                "ordering": ["-received_datetime"],
            },
        ),
        migrations.CreateModel(
            name="HistologyBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_id",
                    models.CharField(
                        help_text="e.g., A, B, C or 1, 2, 3", max_length=20
                    ),
                ),
                ("barcode", models.CharField(blank=True, max_length=100)),
                ("tissue_description", models.CharField(blank=True, max_length=200)),
                ("cassette_color", models.CharField(blank=True, max_length=20)),
                ("embedded_at", models.DateTimeField(blank=True, null=True)),
                ("is_decalcified", models.BooleanField(default=False)),
                (
                    "decalcification_method",
                    models.CharField(blank=True, max_length=100),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "embedded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="embedded_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "histology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="pathology.histology",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histology Block",
                "verbose_name_plural": "Histology Blocks",
                "ordering": ["histology", "block_id"],
                "unique_together": {("histology", "block_id")},
            },
        ),
        migrations.CreateModel(
            name="HistologySlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_number", models.PositiveSmallIntegerField(default=1)),
                ("barcode", models.CharField(blank=True, max_length=100)),
                ("stained_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("ACCEPTABLE", "Acceptable"),
                            ("POOR", "Poor"),
                            ("UNACCEPTABLE", "Unacceptable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quality_notes", models.TextField(blank=True)),
                ("requires_recut", models.BooleanField(default=False)),
                ("is_scanned", models.BooleanField(default=False)),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scan_magnification",
                    models.CharField(
                        blank=True, help_text="e.g., 20x, 40x", max_length=10
                    ),
                ),
                ("scan_file_path", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="pathology.histologyblock",
                    ),
                ),
                (
                    "stained_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stained_slides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slides",
                        to="pathology.stainingprotocol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histology Slide",
                "verbose_name_plural": "Histology Slides",
                "ordering": ["block", "slide_number"],
            },
        ),
        migrations.CreateModel(
            name="TumorSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ICD-O-3 topography code", max_length=10, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("body_system", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subsites",
                        to="pathology.tumorsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tumor Site",
                "verbose_name_plural": "Tumor Sites",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Pathology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pathology_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique pathology report identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "t_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TX", "TX - Primary tumor cannot be assessed"),
                            ("T0", "T0 - No evidence of primary tumor"),
                            ("Tis", "Tis - Carcinoma in situ"),
                            ("T1", "T1"),
                            ("T1a", "T1a"),
                            ("T1b", "T1b"),
                            ("T1c", "T1c"),
                            ("T2", "T2"),
                            ("T2a", "T2a"),
                            ("T2b", "T2b"),
                            ("T3", "T3"),
                            ("T3a", "T3a"),
                            ("T3b", "T3b"),
                            ("T4", "T4"),
                            ("T4a", "T4a"),
                            ("T4b", "T4b"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "n_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NX", "NX - Regional lymph nodes cannot be assessed"),
                            ("N0", "N0 - No regional lymph node metastasis"),
                            ("N1", "N1"),
                            ("N1a", "N1a"),
                            ("N1b", "N1b"),
                            ("N1c", "N1c"),
                            ("N2", "N2"),
                            ("N2a", "N2a"),
                            ("N2b", "N2b"),
                            ("N2c", "N2c"),
                            ("N3", "N3"),
                            ("N3a", "N3a"),
                            ("N3b", "N3b"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "m_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MX", "MX - Distant metastasis cannot be assessed"),
                            ("M0", "M0 - No distant metastasis"),
                            ("M1", "M1 - Distant metastasis"),
                            ("M1a", "M1a"),
                            ("M1b", "M1b"),
                            ("M1c", "M1c"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "stage_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Stage 0"),
                            ("I", "Stage I"),
                            ("IA", "Stage IA"),
                            ("IB", "Stage IB"),
                            ("II", "Stage II"),
                            ("IIA", "Stage IIA"),
                            ("IIB", "Stage IIB"),
                            ("IIC", "Stage IIC"),
                            ("III", "Stage III"),
                            ("IIIA", "Stage IIIA"),
                            ("IIIB", "Stage IIIB"),
                            ("IIIC", "Stage IIIC"),
                            ("IV", "Stage IV"),
                            ("IVA", "Stage IVA"),
                            ("IVB", "Stage IVB"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "clinical_t_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TX", "TX - Primary tumor cannot be assessed"),
                            ("T0", "T0 - No evidence of primary tumor"),
                            ("Tis", "Tis - Carcinoma in situ"),
                            ("T1", "T1"),
                            ("T1a", "T1a"),
                            ("T1b", "T1b"),
                            ("T1c", "T1c"),
                            ("T2", "T2"),
                            ("T2a", "T2a"),
                            ("T2b", "T2b"),
                            ("T3", "T3"),
                            ("T3a", "T3a"),
                            ("T3b", "T3b"),
                            ("T4", "T4"),
                            ("T4a", "T4a"),
                            ("T4b", "T4b"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "clinical_n_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NX", "NX - Regional lymph nodes cannot be assessed"),
                            ("N0", "N0 - No regional lymph node metastasis"),
                            ("N1", "N1"),
                            ("N1a", "N1a"),
                            ("N1b", "N1b"),
                            ("N1c", "N1c"),
                            ("N2", "N2"),
                            ("N2a", "N2a"),
                            ("N2b", "N2b"),
                            ("N2c", "N2c"),
                            ("N3", "N3"),
                            ("N3a", "N3a"),
                            ("N3b", "N3b"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "clinical_m_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MX", "MX - Distant metastasis cannot be assessed"),
                            ("M0", "M0 - No distant metastasis"),
                            ("M1", "M1 - Distant metastasis"),
                            ("M1a", "M1a"),
                            ("M1b", "M1b"),
                            ("M1c", "M1c"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "clinical_stage_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Stage 0"),
                            ("I", "Stage I"),
                            ("IA", "Stage IA"),
                            ("IB", "Stage IB"),
                            ("II", "Stage II"),
                            ("IIA", "Stage IIA"),
                            ("IIB", "Stage IIB"),
                            ("IIC", "Stage IIC"),
                            ("III", "Stage III"),
                            ("IIIA", "Stage IIIA"),
                            ("IIIB", "Stage IIIB"),
                            ("IIIC", "Stage IIIC"),
                            ("IV", "Stage IV"),
                            ("IVA", "Stage IVA"),
                            ("IVB", "Stage IVB"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "staging_system",
                    models.CharField(
                        default="AJCC 8th Edition",
                        help_text="TNM staging system used",
                        max_length=50,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GX", "GX - Grade cannot be assessed"),
                            ("G1", "G1 - Well differentiated"),
                            ("G2", "G2 - Moderately differentiated"),
                            ("G3", "G3 - Poorly differentiated"),
                            ("G4", "G4 - Undifferentiated"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "margin_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEGATIVE", "Negative"),
                            ("POSITIVE", "Positive"),
                            ("CLOSE", "Close"),
                            ("INDETERMINATE", "Indeterminate"),
                            ("NA", "Not Applicable"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "closest_margin_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance to closest margin in mm",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("margin_notes", models.TextField(blank=True)),
                (
                    "lymphovascular_invasion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ABSENT", "Absent"),
                            ("PRESENT", "Present"),
                            ("INDETERMINATE", "Indeterminate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "perineural_invasion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ABSENT", "Absent"),
                            ("PRESENT", "Present"),
                            ("INDETERMINATE", "Indeterminate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lymph_nodes_examined",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "lymph_nodes_positive",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("diagnosis", models.TextField(help_text="Final diagnosis")),
                ("microscopic_description", models.TextField(blank=True)),
                ("gross_description", models.TextField(blank=True)),
                ("comment", models.TextField(blank=True)),
                ("clinical_correlation", models.TextField(blank=True)),
                (
                    "ihc_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="IHC marker results (e.g., {'ER': 'Positive 95%', 'PR': 'Positive 80%'})",
                    ),
                ),
                ("molecular_findings", models.TextField(blank=True)),
                (
                    "synoptic_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured synoptic report data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PRELIMINARY", "Preliminary"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("FINAL", "Final"),
                            ("AMENDED", "Amended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("signed_date", models.DateTimeField(blank=True, null=True)),
                ("signature_hash", models.CharField(blank=True, max_length=64)),
                ("amended_date", models.DateTimeField(blank=True, null=True)),
                ("amendment_reason", models.TextField(blank=True)),
                (
                    "original_diagnosis",
                    models.TextField(
                        blank=True, help_text="Original diagnosis before amendment"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amended_pathology_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pathology_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "histology",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pathology_reports",
                        to="pathology.histology",
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathology_reports",
                        to="lab_management.laborder",
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathology_reports",
                        to="tenants.laboratory",
                    ),
                ),
                (
                    "pathologist",
                    models.ForeignKey(
                        blank=True,
                        help_text="Signing pathologist",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathology_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathology_reports",
                        to="lab_management.patient",
                    ),
                ),
                (
                    "pathology_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="pathology.pathologytype",
                    ),
                ),
                (
                    "tumor_morphology",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pathology_reports",
                        to="pathology.tumormorphology",
                    ),
                ),
                (
                    "tumor_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pathology_reports",
                        to="pathology.tumorsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathology Report",
                "verbose_name_plural": "Pathology Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="histology",
            name="specimen_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="histology_samples",
                to="pathology.tumorsite",
            ),
        ),
        migrations.CreateModel(
            name="PathologyAddendum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addendum_number", models.PositiveSmallIntegerField(default=1)),
                ("content", models.TextField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("signed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pathology_addenda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pathology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addenda",
                        to="pathology.pathology",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathology Addendum",
                "verbose_name_plural": "Pathology Addenda",
                "ordering": ["pathology", "addendum_number"],
                "unique_together": {("pathology", "addendum_number")},
            },
        ),
    ]
