# Generated by Django 6.0.2 on 2026-02-15 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("tenants", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "feed_type",
                    models.CharField(
                        choices=[
                            ("SYSTEM", "System"),
                            ("SAMPLES", "Samples"),
                            ("RESULTS", "Results"),
                            ("QC", "Quality Control"),
                            ("EQUIPMENT", "Equipment"),
                            ("DOCUMENTS", "Documents"),
                            ("ORDERS", "Orders"),
                            ("INVENTORY", "Inventory"),
                            ("COMPLIANCE", "Compliance"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CUSTOM",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "laboratory",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lab-specific feed, or null for global",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_feeds",
                        to="tenants.laboratory",
                    ),
                ),
                (
                    "subscribers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subscribed_feeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Feed",
                "verbose_name_plural": "Activity Feeds",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique message identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("body", models.TextField()),
                ("is_system_message", models.BooleanField(default=False)),
                ("has_attachments", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deleted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="deleted_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="messaging.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "viewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="viewed_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="messaging/attachments/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                ("file_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Attachment",
                "verbose_name_plural": "Message Attachments",
            },
        ),
        migrations.CreateModel(
            name="MessageThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique thread identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "is_broadcast",
                    models.BooleanField(
                        default=False, help_text="Announcement to all recipients"
                    ),
                ),
                ("is_urgent", models.BooleanField(default=False)),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="deleted_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_threads",
                        to="tenants.laboratory",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="received_threads", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Thread",
                "verbose_name_plural": "Message Threads",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="messaging.messagethread",
            ),
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notice_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique notice identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "publish_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL", "All Users"),
                            ("LAB", "Laboratory Staff"),
                            ("MANAGERS", "Managers Only"),
                            ("CUSTOM", "Custom Groups"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Default"),
                            ("INFO", "Information"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("DANGER", "Danger"),
                        ],
                        default="DEFAULT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audience_groups",
                    models.ManyToManyField(
                        blank=True, related_name="notices", to="auth.group"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="tenants.laboratory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notice",
                "verbose_name_plural": "Notices",
                "ordering": ["-is_pinned", "-publish_date"],
            },
        ),
        migrations.CreateModel(
            name="ActivityStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique activity identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("submitted", "Submitted"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("transitioned", "Transitioned"),
                            ("assigned", "Assigned"),
                            ("commented", "Commented"),
                            ("uploaded", "Uploaded"),
                            ("downloaded", "Downloaded"),
                            ("shared", "Shared"),
                            ("started", "Started"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                            ("received", "Received"),
                            ("released", "Released"),
                            ("flagged", "Flagged"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "action_object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of action object",
                        max_length=255,
                    ),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "target_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of target",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("is_public", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "action_object_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_object_activities",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feeds",
                    models.ManyToManyField(
                        blank=True,
                        related_name="activities",
                        to="messaging.activityfeed",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_activities",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "viewers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="viewed_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Stream",
                "verbose_name_plural": "Activity Streams",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-timestamp"],
                        name="messaging_a_actor_i_b916e1_idx",
                    ),
                    models.Index(
                        fields=["verb", "-timestamp"],
                        name="messaging_a_verb_e28c08_idx",
                    ),
                    models.Index(
                        fields=["action_object_content_type", "action_object_id"],
                        name="messaging_a_action__ed9770_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_id",
                    models.CharField(
                        editable=False,
                        help_text="Auto-generated unique notification identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("SUCCESS", "Success"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("ACTION", "Action Required"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "departments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of department names to notify",
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, help_text="Show to all users in organization"
                    ),
                ),
                (
                    "linked_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="URL for notification action",
                        max_length=500,
                    ),
                ),
                ("is_sent", models.BooleanField(default=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("send_email", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dismissed_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dismissed_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="notifications", to="auth.group"
                    ),
                ),
                (
                    "laboratory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tenants.laboratory",
                    ),
                ),
                (
                    "linked_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "read_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="read_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["priority", "-created_at"],
                        name="messaging_n_priorit_c536c2_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "-created_at"],
                        name="messaging_n_notific_0077b3_idx",
                    ),
                ],
            },
        ),
    ]
