# Generated by Django 6.0.2 on 2026-02-15 09:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab_management", "0021_remove_patient_barcode_image_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_number",
                    models.CharField(
                        help_text="Unique transfer identifier",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "source_location",
                    models.CharField(
                        help_text="Origin facility/location", max_length=200
                    ),
                ),
                (
                    "destination_location",
                    models.CharField(
                        help_text="Destination facility/location", max_length=200
                    ),
                ),
                (
                    "transfer_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time when the transfer was initiated",
                    ),
                ),
                (
                    "expected_arrival_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Expected arrival date at destination",
                        null=True,
                    ),
                ),
                (
                    "actual_arrival_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Actual arrival date at destination",
                        null=True,
                    ),
                ),
                (
                    "courier",
                    models.CharField(
                        blank=True,
                        help_text="Courier/shipping company name",
                        max_length=100,
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, help_text="Shipping tracking number", max_length=100
                    ),
                ),
                (
                    "shipment_conditions",
                    models.CharField(
                        choices=[
                            ("AMBIENT", "Ambient Temperature"),
                            ("REFRIGERATED", "Refrigerated (2-8C)"),
                            ("FROZEN_MINUS20", "Frozen (-20C)"),
                            ("FROZEN_MINUS80", "Frozen (-80C)"),
                            ("DRY_ICE", "Dry Ice"),
                            ("LIQUID_NITROGEN", "Liquid Nitrogen"),
                        ],
                        default="AMBIENT",
                        help_text="Temperature/storage conditions during transport",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_TRANSIT", "In Transit"),
                            ("RECEIVED", "Received"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the transfer"
                    ),
                ),
                (
                    "special_instructions",
                    models.TextField(
                        blank=True, help_text="Special handling instructions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who initiated the transfer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who received the transfer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer",
                "verbose_name_plural": "Transfers",
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.CreateModel(
            name="TransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_id",
                    models.CharField(help_text="Sample identifier", max_length=100),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of sample units/aliquots",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "container_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of container (e.g., cryovial, tube)",
                        max_length=100,
                    ),
                ),
                (
                    "storage_position",
                    models.CharField(
                        blank=True,
                        help_text="Position in shipping container/box",
                        max_length=100,
                    ),
                ),
                (
                    "condition_on_departure",
                    models.CharField(
                        blank=True,
                        help_text="Sample condition when sent",
                        max_length=200,
                    ),
                ),
                (
                    "condition_on_arrival",
                    models.CharField(
                        blank=True,
                        help_text="Sample condition when received",
                        max_length=200,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this item"
                    ),
                ),
                (
                    "is_received",
                    models.BooleanField(
                        default=False,
                        help_text="Has this item been received and verified?",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, help_text="When was this item received?", null=True
                    ),
                ),
                (
                    "has_discrepancy",
                    models.BooleanField(
                        default=False,
                        help_text="Is there any discrepancy with this item?",
                    ),
                ),
                (
                    "discrepancy_notes",
                    models.TextField(
                        blank=True, help_text="Description of any discrepancies"
                    ),
                ),
                (
                    "lab_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated lab order (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_items",
                        to="lab_management.laborder",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_transfer_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="transfers.transfer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer Item",
                "verbose_name_plural": "Transfer Items",
                "ordering": ["transfer", "sample_id"],
            },
        ),
    ]
