# Generated by Django 6.0.2 on 2026-02-15 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("PATIENTS", "Patients"),
                            ("SAMPLES", "Samples"),
                            ("RESULTS", "Results"),
                            ("LAB_ORDERS", "Lab Orders"),
                            ("REAGENTS", "Reagents"),
                            ("EQUIPMENT", "Equipment"),
                            ("AUDIT_LOGS", "Audit Logs"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[
                            ("CSV", "CSV"),
                            ("XLSX", "Excel"),
                            ("JSON", "JSON"),
                            ("PDF", "PDF"),
                        ],
                        default="CSV",
                        max_length=10,
                    ),
                ),
                (
                    "included_fields",
                    models.JSONField(
                        default=list,
                        help_text="List of field names to include in export",
                    ),
                ),
                (
                    "field_labels",
                    models.JSONField(
                        default=dict, help_text="Custom labels for fields"
                    ),
                ),
                (
                    "field_order",
                    models.JSONField(
                        default=list, help_text="Order of fields in export"
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(default=dict, help_text="Default filter criteria"),
                ),
                ("date_format", models.CharField(default="%Y-%m-%d", max_length=50)),
                (
                    "datetime_format",
                    models.CharField(default="%Y-%m-%d %H:%M:%S", max_length=50),
                ),
                ("include_headers", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Template",
                "verbose_name_plural": "Export Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_type", models.CharField(max_length=50)),
                ("output_format", models.CharField(default="CSV", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="exports/%Y/%m/"),
                ),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to="data_exchange.exporttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Job",
                "verbose_name_plural": "Export Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("PATIENTS", "Patients"),
                            ("SAMPLES", "Samples"),
                            ("RESULTS", "Results"),
                            ("REAGENTS", "Reagents"),
                            ("EQUIPMENT", "Equipment"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("VALIDATING", "Validating"),
                            ("VALIDATED", "Validated"),
                            ("IMPORTING", "Importing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("source_file", models.FileField(upload_to="imports/%Y/%m/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_format", models.CharField(default="CSV", max_length=20)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("successful_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("import_errors", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "column_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Maps source columns to model fields",
                    ),
                ),
                ("skip_duplicates", models.BooleanField(default=True)),
                ("update_existing", models.BooleanField(default=False)),
                ("dry_run", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Job",
                "verbose_name_plural": "Import Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                            ("DUPLICATE", "Duplicate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="data_exchange.importjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imported Record",
                "verbose_name_plural": "Imported Records",
                "ordering": ["row_number"],
            },
        ),
    ]
