# Generated by Django 6.0.2 on 2026-02-16 09:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("data_exchange", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="System identifier name", max_length=100, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "system_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of system (EHR, LIS, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("HL7V2", "HL7 v2.x"),
                            ("FHIR_R4", "FHIR R4"),
                            ("FHIR_STU3", "FHIR STU3"),
                        ],
                        default="HL7V2",
                        max_length=20,
                    ),
                ),
                (
                    "protocol_version",
                    models.CharField(
                        blank=True,
                        help_text="Protocol version (e.g., 2.5.1, R4)",
                        max_length=20,
                    ),
                ),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("MLLP", "MLLP (TCP/IP)"),
                            ("HTTP", "HTTP/HTTPS"),
                            ("SFTP", "SFTP"),
                            ("FILE", "File System"),
                        ],
                        default="MLLP",
                        max_length=20,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, help_text="Hostname or IP address", max_length=255
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        blank=True, help_text="Port number", null=True
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, help_text="URL path or file path", max_length=500
                    ),
                ),
                (
                    "credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Authentication credentials (encrypted in production)",
                    ),
                ),
                (
                    "hl7_sending_application",
                    models.CharField(
                        default="TRPM-LIMS",
                        help_text="MSH-3: Sending Application",
                        max_length=50,
                    ),
                ),
                (
                    "hl7_sending_facility",
                    models.CharField(
                        blank=True, help_text="MSH-4: Sending Facility", max_length=50
                    ),
                ),
                (
                    "hl7_receiving_application",
                    models.CharField(
                        blank=True,
                        help_text="MSH-5: Receiving Application",
                        max_length=50,
                    ),
                ),
                (
                    "hl7_receiving_facility",
                    models.CharField(
                        blank=True, help_text="MSH-6: Receiving Facility", max_length=50
                    ),
                ),
                (
                    "hl7_version",
                    models.CharField(
                        default="2.5.1", help_text="HL7 Version ID", max_length=10
                    ),
                ),
                (
                    "fhir_base_url",
                    models.URLField(blank=True, help_text="FHIR server base URL"),
                ),
                (
                    "fhir_client_id",
                    models.CharField(
                        blank=True, help_text="OAuth2 client ID", max_length=200
                    ),
                ),
                (
                    "fhir_capabilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Supported FHIR resources/operations",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=30, help_text="Connection timeout in seconds"
                    ),
                ),
                (
                    "retry_attempts",
                    models.PositiveIntegerField(
                        default=3, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "retry_delay_seconds",
                    models.PositiveIntegerField(
                        default=60, help_text="Delay between retries"
                    ),
                ),
                (
                    "message_encoding",
                    models.CharField(
                        default="UTF-8",
                        help_text="Character encoding for messages",
                        max_length=20,
                    ),
                ),
                (
                    "auto_acknowledge",
                    models.BooleanField(
                        default=True, help_text="Automatically send acknowledgments"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("TESTING", "Testing"),
                            ("ERROR", "Error"),
                        ],
                        default="INACTIVE",
                        max_length=20,
                    ),
                ),
                ("last_connection_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "External System",
                "verbose_name_plural": "External Systems",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MessageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("OUTBOUND", "Outbound"), ("INBOUND", "Inbound")],
                        max_length=20,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        db_index=True,
                        help_text="Message Control ID (MSH-10) or FHIR ID",
                        max_length=100,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("ORU_R01", "ORU^R01 - Observation Result"),
                            ("ORM_O01", "ORM^O01 - Order Message"),
                            ("ADT_A01", "ADT^A01 - Admit"),
                            ("ADT_A04", "ADT^A04 - Register"),
                            ("ACK", "ACK - Acknowledgment"),
                            ("FHIR_DIAGNOSTIC_REPORT", "FHIR DiagnosticReport"),
                            ("FHIR_OBSERVATION", "FHIR Observation"),
                            ("FHIR_PATIENT", "FHIR Patient"),
                            ("FHIR_SPECIMEN", "FHIR Specimen"),
                            ("FHIR_BUNDLE", "FHIR Bundle"),
                        ],
                        max_length=50,
                    ),
                ),
                ("raw_message", models.TextField(help_text="Raw message content")),
                (
                    "parsed_message",
                    models.JSONField(
                        blank=True, default=dict, help_text="Parsed message structure"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("FAILED", "Failed"),
                            ("REJECTED", "Rejected"),
                            ("RETRYING", "Retrying"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("status_message", models.TextField(blank=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "acknowledgment_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of acknowledgment message",
                        max_length=100,
                    ),
                ),
                (
                    "acknowledgment_code",
                    models.CharField(
                        blank=True, help_text="ACK code (AA, AE, AR)", max_length=10
                    ),
                ),
                ("acknowledgment_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "external_system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_logs",
                        to="data_exchange.externalsystem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Log",
                "verbose_name_plural": "Message Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["message_id"], name="data_exchan_message_c70a27_idx"
                    ),
                    models.Index(
                        fields=["external_system", "status"],
                        name="data_exchan_externa_2c94ea_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="data_exchan_created_7d662b_idx"
                    ),
                ],
            },
        ),
    ]
