"""
Django settings for lims project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--vt)zzgg!_nhq-%8xkrl8xz2d1yc2%d*mf-(=1gqkx5c=35c)%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'corsheaders',

    # Core LIMS apps
    'lab_management',
    'reagents',
    'molecular_diagnostics',
    'equipment',
    'storage',

    # Phase 1 apps
    'api',
    'users',
    'audit',
    'data_exchange',

    # Phase 2 apps
    'analytics',
    'transfers',
    'compliance',

    # Phase 3 apps
    'instruments',

    # Phase 4 apps - Feature gaps implementation
    'tenants',           # Multi-tenant architecture
    'single_cell',       # Single-cell genomics support
    'bioinformatics',    # Pipeline management (drylab)
    'ontology',          # Disease ontology integration
    'sensors',           # Environmental monitoring
    'dynamic_fields',    # Dynamic field creation
    'projects',          # Project-based organization
    'billing',           # Financial/billing module

    # Phase 5 apps - Additional features
    'microbiology',      # Antibiotic susceptibility testing (AST)
    'qms',               # Quality management system (document management)
    'messaging',         # Messaging, notifications, activity streams
    'pathology',         # Histology/pathology with TNM staging

    # Phase 6 apps - Molecular/Genomics Enhancements
    'pharmacogenomics',  # PGx module for drug-gene interactions
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'audit.middleware.AuditMiddleware',
    'users.middleware.UserActivityMiddleware',
    'tenants.middleware.TenantMiddleware',
]

ROOT_URLCONF = 'lims.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Ensure the 'templates' directory is listed here
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'lims.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Add the path to your static files directory
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Assuming "static" folder is in your project root
]



# Set up media configurations
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # The directory where your media files (like barcode images) are stored


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Laboratory settings for report generation
LAB_NAME = 'Translational Research and Precision Medicine Lab'
LAB_ADDRESS = ''
LAB_PHONE = ''
LAB_ACCREDITATION = ''

# Django REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# drf-spectacular settings for API documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'TRPM-LIMS API',
    'DESCRIPTION': 'REST API for Translational Research and Precision Medicine Laboratory Information Management System',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS settings (for development - restrict in production)
CORS_ALLOW_ALL_ORIGINS = DEBUG

# Celery Configuration (for background tasks)
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# ===========================================
# Variant Annotation Settings
# ===========================================

# NCBI E-utilities (ClinVar)
NCBI_API_KEY = os.environ.get('NCBI_API_KEY', '')
NCBI_EMAIL = os.environ.get('NCBI_EMAIL', 'admin@trpm-lims.org')

# Annotation cache settings
ANNOTATION_CACHE_TTL_DAYS = 30

# ===========================================
# HL7/FHIR Integration Settings
# ===========================================

# FHIR server configuration
FHIR_BASE_URL = os.environ.get('FHIR_BASE_URL', 'http://localhost:8000/fhir')
